// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        data_V_V_dout,
        data_V_V_empty_n,
        data_V_V_read,
        res_V_V_din,
        res_V_V_full_n,
        res_V_V_write
);

parameter    ap_ST_fsm_state1 = 28'd1;
parameter    ap_ST_fsm_state2 = 28'd2;
parameter    ap_ST_fsm_state3 = 28'd4;
parameter    ap_ST_fsm_state4 = 28'd8;
parameter    ap_ST_fsm_state5 = 28'd16;
parameter    ap_ST_fsm_pp0_stage0 = 28'd32;
parameter    ap_ST_fsm_state12 = 28'd64;
parameter    ap_ST_fsm_state13 = 28'd128;
parameter    ap_ST_fsm_state14 = 28'd256;
parameter    ap_ST_fsm_state15 = 28'd512;
parameter    ap_ST_fsm_state16 = 28'd1024;
parameter    ap_ST_fsm_state17 = 28'd2048;
parameter    ap_ST_fsm_state18 = 28'd4096;
parameter    ap_ST_fsm_state19 = 28'd8192;
parameter    ap_ST_fsm_state20 = 28'd16384;
parameter    ap_ST_fsm_state21 = 28'd32768;
parameter    ap_ST_fsm_state22 = 28'd65536;
parameter    ap_ST_fsm_state23 = 28'd131072;
parameter    ap_ST_fsm_state24 = 28'd262144;
parameter    ap_ST_fsm_state25 = 28'd524288;
parameter    ap_ST_fsm_state26 = 28'd1048576;
parameter    ap_ST_fsm_state27 = 28'd2097152;
parameter    ap_ST_fsm_state28 = 28'd4194304;
parameter    ap_ST_fsm_state29 = 28'd8388608;
parameter    ap_ST_fsm_state30 = 28'd16777216;
parameter    ap_ST_fsm_state31 = 28'd33554432;
parameter    ap_ST_fsm_state32 = 28'd67108864;
parameter    ap_ST_fsm_state33 = 28'd134217728;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [15:0] data_V_V_dout;
input   data_V_V_empty_n;
output   data_V_V_read;
output  [15:0] res_V_V_din;
input   res_V_V_full_n;
output   res_V_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg data_V_V_read;
reg res_V_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [27:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [4:0] layer_in_V_9_address0;
reg    layer_in_V_9_ce0;
reg    layer_in_V_9_we0;
wire   [15:0] layer_in_V_9_q0;
reg   [31:0] sX_4;
reg   [31:0] sY_4;
reg   [31:0] pY_4;
reg   [31:0] pX_4;
wire   [4:0] w2_V_address0;
reg    w2_V_ce0;
wire   [190:0] w2_V_q0;
reg    data_V_V_blk_n;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln247_fu_1130_p2;
reg    res_V_V_blk_n;
wire    ap_CS_fsm_state30;
reg   [15:0] acc_V_31_0_reg_660;
reg   [15:0] acc_V_30_0_reg_673;
reg   [15:0] acc_V_29_0_reg_686;
reg   [15:0] acc_V_28_0_reg_699;
reg   [15:0] acc_V_27_0_reg_712;
reg   [15:0] acc_V_26_0_reg_725;
reg   [15:0] acc_V_25_0_reg_738;
reg   [15:0] acc_V_24_0_reg_751;
reg   [15:0] acc_V_23_0_reg_764;
reg   [15:0] acc_V_22_0_reg_777;
reg   [15:0] acc_V_21_0_reg_790;
reg   [15:0] acc_V_20_0_reg_803;
reg   [15:0] acc_V_19_0_reg_816;
reg   [15:0] acc_V_18_0_reg_829;
reg   [15:0] acc_V_17_0_reg_842;
reg   [15:0] acc_V_16_0_reg_855;
reg   [15:0] acc_V_15_0_reg_868;
reg   [15:0] acc_V_14_0_reg_881;
reg   [15:0] acc_V_13_0_reg_894;
reg   [15:0] acc_V_12_0_reg_907;
reg   [15:0] acc_V_11_0_reg_920;
reg   [15:0] acc_V_10_0_reg_933;
reg   [15:0] acc_V_9_0_reg_946;
reg   [15:0] acc_V_8_0_reg_959;
reg   [15:0] acc_V_7_0_reg_972;
reg   [15:0] acc_V_6_0_reg_985;
reg   [15:0] acc_V_5_0_reg_998;
reg   [15:0] acc_V_4_0_reg_1011;
reg   [15:0] acc_V_3_0_reg_1024;
reg   [15:0] acc_V_2_0_reg_1037;
reg   [15:0] acc_V_1_0_reg_1050;
reg   [15:0] acc_V_0_0_reg_1063;
reg   [4:0] in_index_reg_1076;
reg    ap_block_state1;
wire   [10:0] i_fu_1124_p2;
reg   [10:0] i_reg_2593;
wire    ap_CS_fsm_state2;
wire   [1:0] i1_fu_1136_p2;
reg   [1:0] i1_reg_2601;
reg    ap_block_state3;
reg   [15:0] tmp_V_reg_2606;
reg   [31:0] sX_4_load_reg_2611;
wire    ap_CS_fsm_state5;
wire    grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_ready;
wire    grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done;
wire   [0:0] icmp_ln255_fu_1151_p2;
reg   [0:0] icmp_ln255_reg_2616;
reg   [31:0] sY_4_load_reg_2621;
wire   [0:0] icmp_ln255_7_fu_1161_p2;
reg   [0:0] icmp_ln255_7_reg_2626;
reg   [31:0] pY_4_load_reg_2631;
reg   [31:0] pX_4_load_reg_2637;
wire   [0:0] and_ln255_6_fu_1219_p2;
reg   [0:0] and_ln255_6_reg_2643;
wire   [0:0] icmp_ln336_fu_1225_p2;
reg   [0:0] icmp_ln336_reg_2647;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state6_pp0_stage0_iter0;
wire    ap_block_state7_pp0_stage0_iter1;
wire    ap_block_state8_pp0_stage0_iter2;
wire    ap_block_state9_pp0_stage0_iter3;
wire    ap_block_state10_pp0_stage0_iter4;
wire    ap_block_state11_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln336_reg_2647_pp0_iter1_reg;
reg   [0:0] icmp_ln336_reg_2647_pp0_iter2_reg;
reg   [0:0] icmp_ln336_reg_2647_pp0_iter3_reg;
reg   [0:0] icmp_ln336_reg_2647_pp0_iter4_reg;
wire   [4:0] ir_fu_1231_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [15:0] layer_in_V_9_load_reg_2666;
wire   [5:0] trunc_ln344_fu_1243_p1;
reg  signed [5:0] trunc_ln344_reg_2671;
reg  signed [5:0] tmp_96_reg_2676;
reg  signed [5:0] tmp_97_reg_2681;
reg  signed [5:0] tmp_98_reg_2686;
reg  signed [5:0] tmp_99_reg_2691;
reg  signed [5:0] tmp_100_reg_2696;
reg  signed [5:0] tmp_101_reg_2701;
reg  signed [5:0] tmp_102_reg_2706;
reg  signed [5:0] tmp_103_reg_2711;
reg  signed [5:0] tmp_104_reg_2716;
reg  signed [5:0] tmp_105_reg_2721;
reg  signed [5:0] tmp_106_reg_2726;
reg  signed [5:0] tmp_107_reg_2731;
reg  signed [5:0] tmp_108_reg_2736;
reg  signed [5:0] tmp_109_reg_2741;
reg  signed [5:0] tmp_110_reg_2746;
reg  signed [5:0] tmp_111_reg_2751;
reg  signed [5:0] tmp_112_reg_2756;
reg  signed [5:0] tmp_113_reg_2761;
reg  signed [5:0] tmp_114_reg_2766;
reg  signed [5:0] tmp_115_reg_2771;
reg  signed [5:0] tmp_116_reg_2776;
reg  signed [5:0] tmp_117_reg_2781;
reg  signed [5:0] tmp_118_reg_2786;
reg  signed [5:0] tmp_119_reg_2791;
reg  signed [5:0] tmp_120_reg_2796;
reg  signed [5:0] tmp_121_reg_2801;
reg  signed [5:0] tmp_122_reg_2806;
reg  signed [5:0] tmp_123_reg_2811;
reg  signed [5:0] tmp_124_reg_2816;
reg  signed [5:0] tmp_125_reg_2821;
reg  signed [4:0] tmp_126_reg_2826;
wire  signed [20:0] sext_ln1116_cast_fu_1557_p1;
reg   [15:0] trunc_ln708_31_reg_3027;
wire  signed [20:0] grp_fu_2244_p2;
reg  signed [20:0] mul_ln1118_reg_3032;
wire  signed [20:0] grp_fu_2250_p2;
reg  signed [20:0] mul_ln1118_99_reg_3037;
wire  signed [20:0] grp_fu_2256_p2;
reg  signed [20:0] mul_ln1118_100_reg_3042;
wire  signed [20:0] grp_fu_2262_p2;
reg  signed [20:0] mul_ln1118_101_reg_3047;
wire  signed [20:0] grp_fu_2268_p2;
reg  signed [20:0] mul_ln1118_102_reg_3052;
wire  signed [20:0] grp_fu_2274_p2;
reg  signed [20:0] mul_ln1118_103_reg_3057;
wire  signed [20:0] grp_fu_2280_p2;
reg  signed [20:0] mul_ln1118_104_reg_3062;
wire  signed [20:0] grp_fu_2286_p2;
reg  signed [20:0] mul_ln1118_105_reg_3067;
wire  signed [20:0] grp_fu_2292_p2;
reg  signed [20:0] mul_ln1118_106_reg_3072;
wire  signed [20:0] grp_fu_2298_p2;
reg  signed [20:0] mul_ln1118_107_reg_3077;
wire  signed [20:0] grp_fu_2304_p2;
reg  signed [20:0] mul_ln1118_108_reg_3082;
wire  signed [20:0] grp_fu_2310_p2;
reg  signed [20:0] mul_ln1118_109_reg_3087;
wire  signed [20:0] grp_fu_2316_p2;
reg  signed [20:0] mul_ln1118_110_reg_3092;
wire  signed [20:0] grp_fu_2322_p2;
reg  signed [20:0] mul_ln1118_111_reg_3097;
wire  signed [20:0] grp_fu_2328_p2;
reg  signed [20:0] mul_ln1118_112_reg_3102;
wire  signed [20:0] grp_fu_2334_p2;
reg  signed [20:0] mul_ln1118_113_reg_3107;
wire  signed [20:0] grp_fu_2340_p2;
reg  signed [20:0] mul_ln1118_114_reg_3112;
wire  signed [20:0] grp_fu_2346_p2;
reg  signed [20:0] mul_ln1118_115_reg_3117;
wire  signed [20:0] grp_fu_2352_p2;
reg  signed [20:0] mul_ln1118_116_reg_3122;
wire  signed [20:0] grp_fu_2358_p2;
reg  signed [20:0] mul_ln1118_117_reg_3127;
wire  signed [20:0] grp_fu_2364_p2;
reg  signed [20:0] mul_ln1118_118_reg_3132;
wire  signed [20:0] grp_fu_2370_p2;
reg  signed [20:0] mul_ln1118_119_reg_3137;
wire  signed [20:0] grp_fu_2376_p2;
reg  signed [20:0] mul_ln1118_120_reg_3142;
wire  signed [20:0] grp_fu_2382_p2;
reg  signed [20:0] mul_ln1118_121_reg_3147;
wire  signed [20:0] grp_fu_2388_p2;
reg  signed [20:0] mul_ln1118_122_reg_3152;
wire  signed [20:0] grp_fu_2394_p2;
reg  signed [20:0] mul_ln1118_123_reg_3157;
wire  signed [20:0] grp_fu_2400_p2;
reg  signed [20:0] mul_ln1118_124_reg_3162;
wire  signed [20:0] grp_fu_2406_p2;
reg  signed [20:0] mul_ln1118_125_reg_3167;
wire  signed [20:0] grp_fu_2412_p2;
reg  signed [20:0] mul_ln1118_126_reg_3172;
wire  signed [20:0] grp_fu_2418_p2;
reg  signed [20:0] mul_ln1118_127_reg_3177;
wire  signed [20:0] grp_fu_2424_p2;
reg  signed [20:0] mul_ln1118_128_reg_3182;
wire   [15:0] acc_31_V_fu_1672_p2;
reg   [15:0] acc_31_V_reg_3187;
reg    ap_enable_reg_pp0_iter4;
wire   [15:0] acc_0_V_fu_1956_p2;
reg    ap_enable_reg_pp0_iter5;
wire   [15:0] acc_1_V_fu_1962_p2;
wire   [15:0] acc_2_V_fu_1968_p2;
wire   [15:0] acc_3_V_fu_1974_p2;
wire   [15:0] acc_4_V_fu_1980_p2;
wire   [15:0] acc_5_V_fu_1986_p2;
wire   [15:0] acc_6_V_fu_1992_p2;
wire   [15:0] acc_7_V_fu_1998_p2;
wire   [15:0] acc_8_V_fu_2004_p2;
wire   [15:0] acc_9_V_fu_2010_p2;
wire   [15:0] acc_10_V_fu_2016_p2;
wire   [15:0] acc_11_V_fu_2022_p2;
wire   [15:0] acc_12_V_fu_2028_p2;
wire   [15:0] acc_13_V_fu_2034_p2;
wire   [15:0] acc_14_V_fu_2040_p2;
wire   [15:0] acc_15_V_fu_2046_p2;
wire   [15:0] acc_16_V_fu_2052_p2;
wire   [15:0] acc_17_V_fu_2058_p2;
wire   [15:0] acc_18_V_fu_2064_p2;
wire   [15:0] acc_19_V_fu_2070_p2;
wire   [15:0] acc_20_V_fu_2076_p2;
wire   [15:0] acc_21_V_fu_2082_p2;
wire   [15:0] acc_22_V_fu_2088_p2;
wire   [15:0] acc_23_V_fu_2094_p2;
wire   [15:0] acc_24_V_fu_2100_p2;
wire   [15:0] acc_25_V_fu_2106_p2;
wire   [15:0] acc_26_V_fu_2112_p2;
wire   [15:0] acc_27_V_fu_2118_p2;
wire   [15:0] acc_28_V_fu_2124_p2;
wire   [15:0] acc_29_V_fu_2130_p2;
wire   [15:0] acc_30_V_fu_2136_p2;
wire   [5:0] i_ic_fu_2148_p2;
reg   [5:0] i_ic_reg_3350;
wire    ap_CS_fsm_state28;
wire   [0:0] icmp_ln266_fu_2142_p2;
wire   [0:0] icmp_ln277_fu_2159_p2;
reg   [0:0] icmp_ln277_reg_3360;
wire   [31:0] select_ln292_fu_2180_p3;
reg   [31:0] select_ln292_reg_3364;
wire   [31:0] select_ln287_fu_2220_p3;
reg   [31:0] select_ln287_reg_3372;
wire   [0:0] icmp_ln281_fu_2199_p2;
wire   [15:0] layer_out_i_q0;
reg   [15:0] res_pack_V_reg_3377;
wire    ap_CS_fsm_state29;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state6;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg   [1:0] tmpdata_V_address0;
reg    tmpdata_V_ce0;
reg    tmpdata_V_we0;
wire   [15:0] tmpdata_V_q0;
reg   [4:0] layer_out_i_address0;
reg    layer_out_i_ce0;
reg    layer_out_i_we0;
reg   [15:0] layer_out_i_d0;
reg   [4:0] layer_out_i_address1;
reg    layer_out_i_ce1;
reg    layer_out_i_we1;
reg   [15:0] layer_out_i_d1;
wire    grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_start;
wire    grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_idle;
wire   [1:0] grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_data_V_address0;
wire    grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_data_V_ce0;
wire   [4:0] grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_output_V_address0;
wire    grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_output_V_ce0;
wire    grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_output_V_we0;
wire   [15:0] grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_output_V_d0;
reg   [10:0] i_0_i_reg_637;
wire    ap_CS_fsm_state33;
reg   [1:0] i1_0_i_reg_648;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln245_fu_1118_p2;
reg   [15:0] ap_phi_mux_acc_V_31_0_phi_fu_665_p4;
wire    ap_block_pp0_stage0;
reg   [5:0] i_ic_0_i_reg_1087;
wire    ap_CS_fsm_state27;
reg   [31:0] storemerge_i_reg_1098;
wire    ap_CS_fsm_state32;
reg    grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_start_reg;
reg    ap_block_state3_ignore_call0;
wire   [63:0] zext_ln249_fu_1142_p1;
wire   [63:0] zext_ln344_fu_1237_p1;
wire   [63:0] zext_ln268_fu_2154_p1;
wire    ap_CS_fsm_state31;
wire   [31:0] add_ln285_fu_2204_p2;
wire   [31:0] add_ln290_fu_2164_p2;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state26;
wire   [30:0] tmp_127_fu_1171_p4;
wire   [30:0] tmp_128_fu_1191_p4;
wire   [0:0] icmp_ln255_8_fu_1181_p2;
wire   [0:0] icmp_ln255_9_fu_1201_p2;
wire   [0:0] and_ln255_5_fu_1213_p2;
wire   [0:0] and_ln255_fu_1207_p2;
wire  signed [15:0] grp_fu_1656_p1;
wire   [20:0] grp_fu_1656_p2;
wire   [15:0] trunc_ln_fu_1677_p4;
wire   [15:0] trunc_ln708_1_fu_1686_p4;
wire   [15:0] trunc_ln708_2_fu_1695_p4;
wire   [15:0] trunc_ln708_3_fu_1704_p4;
wire   [15:0] trunc_ln708_4_fu_1713_p4;
wire   [15:0] trunc_ln708_5_fu_1722_p4;
wire   [15:0] trunc_ln708_6_fu_1731_p4;
wire   [15:0] trunc_ln708_7_fu_1740_p4;
wire   [15:0] trunc_ln708_8_fu_1749_p4;
wire   [15:0] trunc_ln708_9_fu_1758_p4;
wire   [15:0] trunc_ln708_10_fu_1767_p4;
wire   [15:0] trunc_ln708_11_fu_1776_p4;
wire   [15:0] trunc_ln708_12_fu_1785_p4;
wire   [15:0] trunc_ln708_13_fu_1794_p4;
wire   [15:0] trunc_ln708_14_fu_1803_p4;
wire   [15:0] trunc_ln708_15_fu_1812_p4;
wire   [15:0] trunc_ln708_16_fu_1821_p4;
wire   [15:0] trunc_ln708_17_fu_1830_p4;
wire   [15:0] trunc_ln708_18_fu_1839_p4;
wire   [15:0] trunc_ln708_19_fu_1848_p4;
wire   [15:0] trunc_ln708_20_fu_1857_p4;
wire   [15:0] trunc_ln708_21_fu_1866_p4;
wire   [15:0] trunc_ln708_22_fu_1875_p4;
wire   [15:0] trunc_ln708_23_fu_1884_p4;
wire   [15:0] trunc_ln708_24_fu_1893_p4;
wire   [15:0] trunc_ln708_25_fu_1902_p4;
wire   [15:0] trunc_ln708_26_fu_1911_p4;
wire   [15:0] trunc_ln708_27_fu_1920_p4;
wire   [15:0] trunc_ln708_28_fu_1929_p4;
wire   [15:0] trunc_ln708_29_fu_1938_p4;
wire   [15:0] trunc_ln708_30_fu_1947_p4;
wire   [31:0] add_ln292_fu_2175_p2;
wire   [31:0] add_ln287_fu_2215_p2;
wire  signed [15:0] grp_fu_2244_p1;
wire  signed [15:0] grp_fu_2250_p1;
wire  signed [15:0] grp_fu_2256_p1;
wire  signed [15:0] grp_fu_2262_p1;
wire  signed [15:0] grp_fu_2268_p1;
wire  signed [15:0] grp_fu_2274_p1;
wire  signed [15:0] grp_fu_2280_p1;
wire  signed [15:0] grp_fu_2286_p1;
wire  signed [15:0] grp_fu_2292_p1;
wire  signed [15:0] grp_fu_2298_p1;
wire  signed [15:0] grp_fu_2304_p1;
wire  signed [15:0] grp_fu_2310_p1;
wire  signed [15:0] grp_fu_2316_p1;
wire  signed [15:0] grp_fu_2322_p1;
wire  signed [15:0] grp_fu_2328_p1;
wire  signed [15:0] grp_fu_2334_p1;
wire  signed [15:0] grp_fu_2340_p1;
wire  signed [15:0] grp_fu_2346_p1;
wire  signed [15:0] grp_fu_2352_p1;
wire  signed [15:0] grp_fu_2358_p1;
wire  signed [15:0] grp_fu_2364_p1;
wire  signed [15:0] grp_fu_2370_p1;
wire  signed [15:0] grp_fu_2376_p1;
wire  signed [15:0] grp_fu_2382_p1;
wire  signed [15:0] grp_fu_2388_p1;
wire  signed [15:0] grp_fu_2394_p1;
wire  signed [15:0] grp_fu_2400_p1;
wire  signed [15:0] grp_fu_2406_p1;
wire  signed [15:0] grp_fu_2412_p1;
wire  signed [15:0] grp_fu_2418_p1;
wire  signed [15:0] grp_fu_2424_p1;
reg   [27:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_623;
reg    ap_condition_839;
reg    ap_condition_634;
reg    ap_condition_781;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 28'd1;
#0 sX_4 = 32'd0;
#0 sY_4 = 32'd0;
#0 pY_4 = 32'd0;
#0 pX_4 = 32'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_start_reg = 1'b0;
end

conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_layecud #(
    .DataWidth( 16 ),
    .AddressRange( 27 ),
    .AddressWidth( 5 ))
layer_in_V_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer_in_V_9_address0),
    .ce0(layer_in_V_9_ce0),
    .we0(layer_in_V_9_we0),
    .d0(grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_output_V_d0),
    .q0(layer_in_V_9_q0)
);

conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_w2_V #(
    .DataWidth( 191 ),
    .AddressRange( 27 ),
    .AddressWidth( 5 ))
w2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_V_address0),
    .ce0(w2_V_ce0),
    .q0(w2_V_q0)
);

conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_tmpddEe #(
    .DataWidth( 16 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
tmpdata_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tmpdata_V_address0),
    .ce0(tmpdata_V_ce0),
    .we0(tmpdata_V_we0),
    .d0(tmp_V_reg_2606),
    .q0(tmpdata_V_q0)
);

conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_layeeOg #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
layer_out_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer_out_i_address0),
    .ce0(layer_out_i_ce0),
    .we0(layer_out_i_we0),
    .d0(layer_out_i_d0),
    .q0(layer_out_i_q0),
    .address1(layer_out_i_address1),
    .ce1(layer_out_i_ce1),
    .we1(layer_out_i_we1),
    .d1(layer_out_i_d1)
);

cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_start),
    .ap_done(grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done),
    .ap_idle(grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_idle),
    .ap_ready(grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_ready),
    .data_V_address0(grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_data_V_address0),
    .data_V_ce0(grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_data_V_ce0),
    .data_V_q0(tmpdata_V_q0),
    .output_V_address0(grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_output_V_address0),
    .output_V_ce0(grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_output_V_ce0),
    .output_V_we0(grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_output_V_we0),
    .output_V_d0(grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_output_V_d0),
    .output_V_q0(layer_in_V_9_q0)
);

myproject_axi_mul_5s_16s_21_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_5s_16s_21_2_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_126_reg_2826),
    .din1(grp_fu_1656_p1),
    .ce(1'b1),
    .dout(grp_fu_1656_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln344_reg_2671),
    .din1(grp_fu_2244_p1),
    .ce(1'b1),
    .dout(grp_fu_2244_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_96_reg_2676),
    .din1(grp_fu_2250_p1),
    .ce(1'b1),
    .dout(grp_fu_2250_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_97_reg_2681),
    .din1(grp_fu_2256_p1),
    .ce(1'b1),
    .dout(grp_fu_2256_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_98_reg_2686),
    .din1(grp_fu_2262_p1),
    .ce(1'b1),
    .dout(grp_fu_2262_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_99_reg_2691),
    .din1(grp_fu_2268_p1),
    .ce(1'b1),
    .dout(grp_fu_2268_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_100_reg_2696),
    .din1(grp_fu_2274_p1),
    .ce(1'b1),
    .dout(grp_fu_2274_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_101_reg_2701),
    .din1(grp_fu_2280_p1),
    .ce(1'b1),
    .dout(grp_fu_2280_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_102_reg_2706),
    .din1(grp_fu_2286_p1),
    .ce(1'b1),
    .dout(grp_fu_2286_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_103_reg_2711),
    .din1(grp_fu_2292_p1),
    .ce(1'b1),
    .dout(grp_fu_2292_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_104_reg_2716),
    .din1(grp_fu_2298_p1),
    .ce(1'b1),
    .dout(grp_fu_2298_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_105_reg_2721),
    .din1(grp_fu_2304_p1),
    .ce(1'b1),
    .dout(grp_fu_2304_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_106_reg_2726),
    .din1(grp_fu_2310_p1),
    .ce(1'b1),
    .dout(grp_fu_2310_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_107_reg_2731),
    .din1(grp_fu_2316_p1),
    .ce(1'b1),
    .dout(grp_fu_2316_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_108_reg_2736),
    .din1(grp_fu_2322_p1),
    .ce(1'b1),
    .dout(grp_fu_2322_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_109_reg_2741),
    .din1(grp_fu_2328_p1),
    .ce(1'b1),
    .dout(grp_fu_2328_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_110_reg_2746),
    .din1(grp_fu_2334_p1),
    .ce(1'b1),
    .dout(grp_fu_2334_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_111_reg_2751),
    .din1(grp_fu_2340_p1),
    .ce(1'b1),
    .dout(grp_fu_2340_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_112_reg_2756),
    .din1(grp_fu_2346_p1),
    .ce(1'b1),
    .dout(grp_fu_2346_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_113_reg_2761),
    .din1(grp_fu_2352_p1),
    .ce(1'b1),
    .dout(grp_fu_2352_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_114_reg_2766),
    .din1(grp_fu_2358_p1),
    .ce(1'b1),
    .dout(grp_fu_2358_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_115_reg_2771),
    .din1(grp_fu_2364_p1),
    .ce(1'b1),
    .dout(grp_fu_2364_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_116_reg_2776),
    .din1(grp_fu_2370_p1),
    .ce(1'b1),
    .dout(grp_fu_2370_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_117_reg_2781),
    .din1(grp_fu_2376_p1),
    .ce(1'b1),
    .dout(grp_fu_2376_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_118_reg_2786),
    .din1(grp_fu_2382_p1),
    .ce(1'b1),
    .dout(grp_fu_2382_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_119_reg_2791),
    .din1(grp_fu_2388_p1),
    .ce(1'b1),
    .dout(grp_fu_2388_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U35(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_120_reg_2796),
    .din1(grp_fu_2394_p1),
    .ce(1'b1),
    .dout(grp_fu_2394_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_121_reg_2801),
    .din1(grp_fu_2400_p1),
    .ce(1'b1),
    .dout(grp_fu_2400_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_122_reg_2806),
    .din1(grp_fu_2406_p1),
    .ce(1'b1),
    .dout(grp_fu_2406_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_123_reg_2811),
    .din1(grp_fu_2412_p1),
    .ce(1'b1),
    .dout(grp_fu_2412_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_124_reg_2816),
    .din1(grp_fu_2418_p1),
    .ce(1'b1),
    .dout(grp_fu_2418_p2)
);

myproject_axi_mul_mul_6s_16s_21_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
myproject_axi_mul_mul_6s_16s_21_3_1_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_125_reg_2821),
    .din1(grp_fu_2424_p1),
    .ce(1'b1),
    .dout(grp_fu_2424_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln245_fu_1118_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state6) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state6)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state6);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_start_reg <= 1'b0;
    end else begin
        if ((~((icmp_ln247_fu_1130_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln247_fu_1130_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_start_reg <= 1'b1;
        end else if ((grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_ready == 1'b1)) begin
            grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_0_0_reg_1063 <= acc_0_V_fu_1956_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_0_0_reg_1063 <= 16'd256;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_10_0_reg_933 <= acc_10_V_fu_2016_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_10_0_reg_933 <= 16'd128;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_11_0_reg_920 <= acc_11_V_fu_2022_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_11_0_reg_920 <= 16'd128;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_12_0_reg_907 <= acc_12_V_fu_2028_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_12_0_reg_907 <= 16'd256;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_13_0_reg_894 <= acc_13_V_fu_2034_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_13_0_reg_894 <= 16'd256;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_14_0_reg_881 <= acc_14_V_fu_2040_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_14_0_reg_881 <= 16'd256;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_15_0_reg_868 <= acc_15_V_fu_2046_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_15_0_reg_868 <= 16'd256;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_16_0_reg_855 <= acc_16_V_fu_2052_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_16_0_reg_855 <= 16'd65408;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_17_0_reg_842 <= acc_17_V_fu_2058_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_17_0_reg_842 <= 16'd128;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_18_0_reg_829 <= acc_18_V_fu_2064_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_18_0_reg_829 <= 16'd128;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_19_0_reg_816 <= acc_19_V_fu_2070_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_19_0_reg_816 <= 16'd256;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_1_0_reg_1050 <= acc_1_V_fu_1962_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_1_0_reg_1050 <= 16'd128;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_20_0_reg_803 <= acc_20_V_fu_2076_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_20_0_reg_803 <= 16'd128;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_21_0_reg_790 <= acc_21_V_fu_2082_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_21_0_reg_790 <= 16'd256;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_22_0_reg_777 <= acc_22_V_fu_2088_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_22_0_reg_777 <= 16'd128;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_23_0_reg_764 <= acc_23_V_fu_2094_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_23_0_reg_764 <= 16'd256;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_24_0_reg_751 <= acc_24_V_fu_2100_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_24_0_reg_751 <= 16'd65152;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_25_0_reg_738 <= acc_25_V_fu_2106_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_25_0_reg_738 <= 16'd256;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_26_0_reg_725 <= acc_26_V_fu_2112_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_26_0_reg_725 <= 16'd65280;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_27_0_reg_712 <= acc_27_V_fu_2118_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_27_0_reg_712 <= 16'd256;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_28_0_reg_699 <= acc_28_V_fu_2124_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_28_0_reg_699 <= 16'd128;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_29_0_reg_686 <= acc_29_V_fu_2130_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_29_0_reg_686 <= 16'd65408;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_2_0_reg_1037 <= acc_2_V_fu_1968_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_2_0_reg_1037 <= 16'd128;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_30_0_reg_673 <= acc_30_V_fu_2136_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_30_0_reg_673 <= 16'd256;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_31_0_reg_660 <= acc_31_V_reg_3187;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_31_0_reg_660 <= 16'd384;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_3_0_reg_1024 <= acc_3_V_fu_1974_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_3_0_reg_1024 <= 16'd128;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_4_0_reg_1011 <= acc_4_V_fu_1980_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_4_0_reg_1011 <= 16'd256;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_5_0_reg_998 <= acc_5_V_fu_1986_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_5_0_reg_998 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_6_0_reg_985 <= acc_6_V_fu_1992_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_6_0_reg_985 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_7_0_reg_972 <= acc_7_V_fu_1998_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_7_0_reg_972 <= 16'd128;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_8_0_reg_959 <= acc_8_V_fu_2004_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_8_0_reg_959 <= 16'd512;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        acc_V_9_0_reg_946 <= acc_9_V_fu_2010_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_V_9_0_reg_946 <= 16'd512;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln245_fu_1118_p2 == 1'd0))) begin
        i1_0_i_reg_648 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        i1_0_i_reg_648 <= i1_reg_2601;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        i_0_i_reg_637 <= i_reg_2593;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_i_reg_637 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state30))) begin
        i_ic_0_i_reg_1087 <= i_ic_reg_3350;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        i_ic_0_i_reg_1087 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln336_fu_1225_p2 == 1'd0))) begin
        in_index_reg_1076 <= ir_fu_1231_p2;
    end else if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        in_index_reg_1076 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        if ((1'b1 == ap_condition_839)) begin
            pX_4 <= 32'd0;
        end else if ((1'b1 == ap_condition_623)) begin
            pX_4 <= add_ln290_fu_2164_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        if ((1'b1 == ap_condition_781)) begin
            pY_4 <= 32'd0;
        end else if ((1'b1 == ap_condition_634)) begin
            pY_4 <= add_ln285_fu_2204_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        sX_4 <= select_ln292_reg_3364;
    end else if (((1'b1 == ap_CS_fsm_state28) & (((icmp_ln277_fu_2159_p2 == 1'd1) & (1'd0 == and_ln255_6_reg_2643)) | ((icmp_ln277_fu_2159_p2 == 1'd1) & (icmp_ln266_fu_2142_p2 == 1'd1))))) begin
        sX_4 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state28) & (((icmp_ln281_fu_2199_p2 == 1'd1) & (icmp_ln277_fu_2159_p2 == 1'd1) & (1'd0 == and_ln255_6_reg_2643)) | ((icmp_ln281_fu_2199_p2 == 1'd1) & (icmp_ln277_fu_2159_p2 == 1'd1) & (icmp_ln266_fu_2142_p2 == 1'd1))))) begin
        storemerge_i_reg_1098 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        storemerge_i_reg_1098 <= select_ln287_reg_3372;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter3_reg == 1'd0))) begin
        acc_31_V_reg_3187 <= acc_31_V_fu_1672_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        and_ln255_6_reg_2643 <= and_ln255_6_fu_1219_p2;
        icmp_ln255_7_reg_2626 <= icmp_ln255_7_fu_1161_p2;
        icmp_ln255_reg_2616 <= icmp_ln255_fu_1151_p2;
        pX_4_load_reg_2637 <= pX_4;
        pY_4_load_reg_2631 <= pY_4;
        sX_4_load_reg_2611 <= sX_4;
        sY_4_load_reg_2621 <= sY_4;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln247_fu_1130_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        i1_reg_2601 <= i1_fu_1136_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln255_6_reg_2643) & (1'b1 == ap_CS_fsm_state28))) begin
        i_ic_reg_3350 <= i_ic_fu_2148_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_2593 <= i_fu_1124_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state28) & ((icmp_ln266_fu_2142_p2 == 1'd1) | (1'd0 == and_ln255_6_reg_2643)))) begin
        icmp_ln277_reg_3360 <= icmp_ln277_fu_2159_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln336_reg_2647 <= icmp_ln336_fu_1225_p2;
        icmp_ln336_reg_2647_pp0_iter1_reg <= icmp_ln336_reg_2647;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln336_reg_2647_pp0_iter2_reg <= icmp_ln336_reg_2647_pp0_iter1_reg;
        icmp_ln336_reg_2647_pp0_iter3_reg <= icmp_ln336_reg_2647_pp0_iter2_reg;
        icmp_ln336_reg_2647_pp0_iter4_reg <= icmp_ln336_reg_2647_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln336_reg_2647 == 1'd0))) begin
        layer_in_V_9_load_reg_2666 <= layer_in_V_9_q0;
        tmp_100_reg_2696 <= {{w2_V_q0[35:30]}};
        tmp_101_reg_2701 <= {{w2_V_q0[41:36]}};
        tmp_102_reg_2706 <= {{w2_V_q0[47:42]}};
        tmp_103_reg_2711 <= {{w2_V_q0[53:48]}};
        tmp_104_reg_2716 <= {{w2_V_q0[59:54]}};
        tmp_105_reg_2721 <= {{w2_V_q0[65:60]}};
        tmp_106_reg_2726 <= {{w2_V_q0[71:66]}};
        tmp_107_reg_2731 <= {{w2_V_q0[77:72]}};
        tmp_108_reg_2736 <= {{w2_V_q0[83:78]}};
        tmp_109_reg_2741 <= {{w2_V_q0[89:84]}};
        tmp_110_reg_2746 <= {{w2_V_q0[95:90]}};
        tmp_111_reg_2751 <= {{w2_V_q0[101:96]}};
        tmp_112_reg_2756 <= {{w2_V_q0[107:102]}};
        tmp_113_reg_2761 <= {{w2_V_q0[113:108]}};
        tmp_114_reg_2766 <= {{w2_V_q0[119:114]}};
        tmp_115_reg_2771 <= {{w2_V_q0[125:120]}};
        tmp_116_reg_2776 <= {{w2_V_q0[131:126]}};
        tmp_117_reg_2781 <= {{w2_V_q0[137:132]}};
        tmp_118_reg_2786 <= {{w2_V_q0[143:138]}};
        tmp_119_reg_2791 <= {{w2_V_q0[149:144]}};
        tmp_120_reg_2796 <= {{w2_V_q0[155:150]}};
        tmp_121_reg_2801 <= {{w2_V_q0[161:156]}};
        tmp_122_reg_2806 <= {{w2_V_q0[167:162]}};
        tmp_123_reg_2811 <= {{w2_V_q0[173:168]}};
        tmp_124_reg_2816 <= {{w2_V_q0[179:174]}};
        tmp_125_reg_2821 <= {{w2_V_q0[185:180]}};
        tmp_126_reg_2826 <= {{w2_V_q0[190:186]}};
        tmp_96_reg_2676 <= {{w2_V_q0[11:6]}};
        tmp_97_reg_2681 <= {{w2_V_q0[17:12]}};
        tmp_98_reg_2686 <= {{w2_V_q0[23:18]}};
        tmp_99_reg_2691 <= {{w2_V_q0[29:24]}};
        trunc_ln344_reg_2671 <= trunc_ln344_fu_1243_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln336_reg_2647_pp0_iter3_reg == 1'd0))) begin
        mul_ln1118_100_reg_3042 <= grp_fu_2256_p2;
        mul_ln1118_101_reg_3047 <= grp_fu_2262_p2;
        mul_ln1118_102_reg_3052 <= grp_fu_2268_p2;
        mul_ln1118_103_reg_3057 <= grp_fu_2274_p2;
        mul_ln1118_104_reg_3062 <= grp_fu_2280_p2;
        mul_ln1118_105_reg_3067 <= grp_fu_2286_p2;
        mul_ln1118_106_reg_3072 <= grp_fu_2292_p2;
        mul_ln1118_107_reg_3077 <= grp_fu_2298_p2;
        mul_ln1118_108_reg_3082 <= grp_fu_2304_p2;
        mul_ln1118_109_reg_3087 <= grp_fu_2310_p2;
        mul_ln1118_110_reg_3092 <= grp_fu_2316_p2;
        mul_ln1118_111_reg_3097 <= grp_fu_2322_p2;
        mul_ln1118_112_reg_3102 <= grp_fu_2328_p2;
        mul_ln1118_113_reg_3107 <= grp_fu_2334_p2;
        mul_ln1118_114_reg_3112 <= grp_fu_2340_p2;
        mul_ln1118_115_reg_3117 <= grp_fu_2346_p2;
        mul_ln1118_116_reg_3122 <= grp_fu_2352_p2;
        mul_ln1118_117_reg_3127 <= grp_fu_2358_p2;
        mul_ln1118_118_reg_3132 <= grp_fu_2364_p2;
        mul_ln1118_119_reg_3137 <= grp_fu_2370_p2;
        mul_ln1118_120_reg_3142 <= grp_fu_2376_p2;
        mul_ln1118_121_reg_3147 <= grp_fu_2382_p2;
        mul_ln1118_122_reg_3152 <= grp_fu_2388_p2;
        mul_ln1118_123_reg_3157 <= grp_fu_2394_p2;
        mul_ln1118_124_reg_3162 <= grp_fu_2400_p2;
        mul_ln1118_125_reg_3167 <= grp_fu_2406_p2;
        mul_ln1118_126_reg_3172 <= grp_fu_2412_p2;
        mul_ln1118_127_reg_3177 <= grp_fu_2418_p2;
        mul_ln1118_128_reg_3182 <= grp_fu_2424_p2;
        mul_ln1118_99_reg_3037 <= grp_fu_2250_p2;
        mul_ln1118_reg_3032 <= grp_fu_2244_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        res_pack_V_reg_3377 <= layer_out_i_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln277_reg_3360 == 1'd1) & (1'b1 == ap_CS_fsm_state33))) begin
        sY_4 <= storemerge_i_reg_1098;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state28) & (((icmp_ln277_fu_2159_p2 == 1'd1) & (icmp_ln281_fu_2199_p2 == 1'd0) & (1'd0 == and_ln255_6_reg_2643)) | ((icmp_ln277_fu_2159_p2 == 1'd1) & (icmp_ln266_fu_2142_p2 == 1'd1) & (icmp_ln281_fu_2199_p2 == 1'd0))))) begin
        select_ln287_reg_3372 <= select_ln287_fu_2220_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state28) & (((icmp_ln277_fu_2159_p2 == 1'd0) & (1'd0 == and_ln255_6_reg_2643)) | ((icmp_ln266_fu_2142_p2 == 1'd1) & (icmp_ln277_fu_2159_p2 == 1'd0))))) begin
        select_ln292_reg_3364 <= select_ln292_fu_2180_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln247_fu_1130_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln247_fu_1130_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_V_reg_2606 <= data_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln336_reg_2647_pp0_iter2_reg == 1'd0))) begin
        trunc_ln708_31_reg_3027 <= {{grp_fu_1656_p2[20:5]}};
    end
end

always @ (*) begin
    if ((icmp_ln336_fu_1225_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state6 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state6 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln245_fu_1118_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln336_reg_2647_pp0_iter4_reg == 1'd0))) begin
        ap_phi_mux_acc_V_31_0_phi_fu_665_p4 = acc_31_V_reg_3187;
    end else begin
        ap_phi_mux_acc_V_31_0_phi_fu_665_p4 = acc_V_31_0_reg_660;
    end
end

always @ (*) begin
    if (((icmp_ln247_fu_1130_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_V_blk_n = data_V_V_empty_n;
    end else begin
        data_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((icmp_ln247_fu_1130_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln247_fu_1130_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_V_read = 1'b1;
    end else begin
        data_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln245_fu_1118_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer_in_V_9_address0 = zext_ln344_fu_1237_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        layer_in_V_9_address0 = grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_output_V_address0;
    end else begin
        layer_in_V_9_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer_in_V_9_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        layer_in_V_9_ce0 = grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_output_V_ce0;
    end else begin
        layer_in_V_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        layer_in_V_9_we0 = grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_output_V_we0;
    end else begin
        layer_in_V_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        layer_out_i_address0 = zext_ln268_fu_2154_p1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        layer_out_i_address0 = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        layer_out_i_address0 = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        layer_out_i_address0 = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        layer_out_i_address0 = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        layer_out_i_address0 = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        layer_out_i_address0 = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        layer_out_i_address0 = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        layer_out_i_address0 = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        layer_out_i_address0 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        layer_out_i_address0 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        layer_out_i_address0 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        layer_out_i_address0 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        layer_out_i_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        layer_out_i_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        layer_out_i_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        layer_out_i_address0 = 64'd0;
    end else begin
        layer_out_i_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        layer_out_i_address1 = 64'd31;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        layer_out_i_address1 = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        layer_out_i_address1 = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        layer_out_i_address1 = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        layer_out_i_address1 = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        layer_out_i_address1 = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        layer_out_i_address1 = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        layer_out_i_address1 = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        layer_out_i_address1 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        layer_out_i_address1 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        layer_out_i_address1 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        layer_out_i_address1 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        layer_out_i_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        layer_out_i_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        layer_out_i_address1 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        layer_out_i_address1 = 64'd1;
    end else begin
        layer_out_i_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state28))) begin
        layer_out_i_ce0 = 1'b1;
    end else begin
        layer_out_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state27))) begin
        layer_out_i_ce1 = 1'b1;
    end else begin
        layer_out_i_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        layer_out_i_d0 = acc_V_30_0_reg_673;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        layer_out_i_d0 = acc_V_28_0_reg_699;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        layer_out_i_d0 = acc_V_26_0_reg_725;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        layer_out_i_d0 = acc_V_24_0_reg_751;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        layer_out_i_d0 = acc_V_22_0_reg_777;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        layer_out_i_d0 = acc_V_20_0_reg_803;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        layer_out_i_d0 = acc_V_18_0_reg_829;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        layer_out_i_d0 = acc_V_16_0_reg_855;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        layer_out_i_d0 = acc_V_14_0_reg_881;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        layer_out_i_d0 = acc_V_12_0_reg_907;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        layer_out_i_d0 = acc_V_10_0_reg_933;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        layer_out_i_d0 = acc_V_8_0_reg_959;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        layer_out_i_d0 = acc_V_6_0_reg_985;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        layer_out_i_d0 = acc_V_4_0_reg_1011;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        layer_out_i_d0 = acc_V_2_0_reg_1037;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        layer_out_i_d0 = acc_V_0_0_reg_1063;
    end else begin
        layer_out_i_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        layer_out_i_d1 = acc_V_31_0_reg_660;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        layer_out_i_d1 = acc_V_29_0_reg_686;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        layer_out_i_d1 = acc_V_27_0_reg_712;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        layer_out_i_d1 = acc_V_25_0_reg_738;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        layer_out_i_d1 = acc_V_23_0_reg_764;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        layer_out_i_d1 = acc_V_21_0_reg_790;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        layer_out_i_d1 = acc_V_19_0_reg_816;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        layer_out_i_d1 = acc_V_17_0_reg_842;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        layer_out_i_d1 = acc_V_15_0_reg_868;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        layer_out_i_d1 = acc_V_13_0_reg_894;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        layer_out_i_d1 = acc_V_11_0_reg_920;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        layer_out_i_d1 = acc_V_9_0_reg_946;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        layer_out_i_d1 = acc_V_7_0_reg_972;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        layer_out_i_d1 = acc_V_5_0_reg_998;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        layer_out_i_d1 = acc_V_3_0_reg_1024;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        layer_out_i_d1 = acc_V_1_0_reg_1050;
    end else begin
        layer_out_i_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state27))) begin
        layer_out_i_we0 = 1'b1;
    end else begin
        layer_out_i_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state27))) begin
        layer_out_i_we1 = 1'b1;
    end else begin
        layer_out_i_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        res_V_V_blk_n = res_V_V_full_n;
    end else begin
        res_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state30))) begin
        res_V_V_write = 1'b1;
    end else begin
        res_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmpdata_V_address0 = zext_ln249_fu_1142_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmpdata_V_address0 = grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_data_V_address0;
    end else begin
        tmpdata_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmpdata_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmpdata_V_ce0 = grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_data_V_ce0;
    end else begin
        tmpdata_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmpdata_V_we0 = 1'b1;
    end else begin
        tmpdata_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w2_V_ce0 = 1'b1;
    end else begin
        w2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln245_fu_1118_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((icmp_ln247_fu_1130_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln247_fu_1130_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if ((~((icmp_ln247_fu_1130_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln247_fu_1130_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state5 : begin
            if (((1'd1 == and_ln255_6_fu_1219_p2) & (grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5) & (1'd0 == and_ln255_6_fu_1219_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln336_fu_1225_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln336_fu_1225_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            if (((1'b1 == ap_CS_fsm_state28) & (((icmp_ln281_fu_2199_p2 == 1'd1) & (icmp_ln277_fu_2159_p2 == 1'd1) & (1'd0 == and_ln255_6_reg_2643)) | ((icmp_ln281_fu_2199_p2 == 1'd1) & (icmp_ln277_fu_2159_p2 == 1'd1) & (icmp_ln266_fu_2142_p2 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else if (((1'b1 == ap_CS_fsm_state28) & (((icmp_ln277_fu_2159_p2 == 1'd1) & (icmp_ln281_fu_2199_p2 == 1'd0) & (1'd0 == and_ln255_6_reg_2643)) | ((icmp_ln277_fu_2159_p2 == 1'd1) & (icmp_ln266_fu_2142_p2 == 1'd1) & (icmp_ln281_fu_2199_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else if (((1'b1 == ap_CS_fsm_state28) & (((icmp_ln277_fu_2159_p2 == 1'd0) & (1'd0 == and_ln255_6_reg_2643)) | ((icmp_ln266_fu_2142_p2 == 1'd1) & (icmp_ln277_fu_2159_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state30))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_0_V_fu_1956_p2 = (acc_V_0_0_reg_1063 + trunc_ln_fu_1677_p4);

assign acc_10_V_fu_2016_p2 = (acc_V_10_0_reg_933 + trunc_ln708_10_fu_1767_p4);

assign acc_11_V_fu_2022_p2 = (acc_V_11_0_reg_920 + trunc_ln708_11_fu_1776_p4);

assign acc_12_V_fu_2028_p2 = (acc_V_12_0_reg_907 + trunc_ln708_12_fu_1785_p4);

assign acc_13_V_fu_2034_p2 = (acc_V_13_0_reg_894 + trunc_ln708_13_fu_1794_p4);

assign acc_14_V_fu_2040_p2 = (acc_V_14_0_reg_881 + trunc_ln708_14_fu_1803_p4);

assign acc_15_V_fu_2046_p2 = (acc_V_15_0_reg_868 + trunc_ln708_15_fu_1812_p4);

assign acc_16_V_fu_2052_p2 = (acc_V_16_0_reg_855 + trunc_ln708_16_fu_1821_p4);

assign acc_17_V_fu_2058_p2 = (acc_V_17_0_reg_842 + trunc_ln708_17_fu_1830_p4);

assign acc_18_V_fu_2064_p2 = (acc_V_18_0_reg_829 + trunc_ln708_18_fu_1839_p4);

assign acc_19_V_fu_2070_p2 = (acc_V_19_0_reg_816 + trunc_ln708_19_fu_1848_p4);

assign acc_1_V_fu_1962_p2 = (acc_V_1_0_reg_1050 + trunc_ln708_1_fu_1686_p4);

assign acc_20_V_fu_2076_p2 = (acc_V_20_0_reg_803 + trunc_ln708_20_fu_1857_p4);

assign acc_21_V_fu_2082_p2 = (acc_V_21_0_reg_790 + trunc_ln708_21_fu_1866_p4);

assign acc_22_V_fu_2088_p2 = (acc_V_22_0_reg_777 + trunc_ln708_22_fu_1875_p4);

assign acc_23_V_fu_2094_p2 = (acc_V_23_0_reg_764 + trunc_ln708_23_fu_1884_p4);

assign acc_24_V_fu_2100_p2 = (acc_V_24_0_reg_751 + trunc_ln708_24_fu_1893_p4);

assign acc_25_V_fu_2106_p2 = (acc_V_25_0_reg_738 + trunc_ln708_25_fu_1902_p4);

assign acc_26_V_fu_2112_p2 = (acc_V_26_0_reg_725 + trunc_ln708_26_fu_1911_p4);

assign acc_27_V_fu_2118_p2 = (acc_V_27_0_reg_712 + trunc_ln708_27_fu_1920_p4);

assign acc_28_V_fu_2124_p2 = (acc_V_28_0_reg_699 + trunc_ln708_28_fu_1929_p4);

assign acc_29_V_fu_2130_p2 = (acc_V_29_0_reg_686 + trunc_ln708_29_fu_1938_p4);

assign acc_2_V_fu_1968_p2 = (acc_V_2_0_reg_1037 + trunc_ln708_2_fu_1695_p4);

assign acc_30_V_fu_2136_p2 = (acc_V_30_0_reg_673 + trunc_ln708_30_fu_1947_p4);

assign acc_31_V_fu_1672_p2 = (ap_phi_mux_acc_V_31_0_phi_fu_665_p4 + trunc_ln708_31_reg_3027);

assign acc_3_V_fu_1974_p2 = (acc_V_3_0_reg_1024 + trunc_ln708_3_fu_1704_p4);

assign acc_4_V_fu_1980_p2 = (acc_V_4_0_reg_1011 + trunc_ln708_4_fu_1713_p4);

assign acc_5_V_fu_1986_p2 = (acc_V_5_0_reg_998 + trunc_ln708_5_fu_1722_p4);

assign acc_6_V_fu_1992_p2 = (acc_V_6_0_reg_985 + trunc_ln708_6_fu_1731_p4);

assign acc_7_V_fu_1998_p2 = (acc_V_7_0_reg_972 + trunc_ln708_7_fu_1740_p4);

assign acc_8_V_fu_2004_p2 = (acc_V_8_0_reg_959 + trunc_ln708_8_fu_1749_p4);

assign acc_9_V_fu_2010_p2 = (acc_V_9_0_reg_946 + trunc_ln708_9_fu_1758_p4);

assign add_ln285_fu_2204_p2 = (pY_4_load_reg_2631 + 32'd1);

assign add_ln287_fu_2215_p2 = (sY_4_load_reg_2621 + 32'd1);

assign add_ln290_fu_2164_p2 = (pX_4_load_reg_2637 + 32'd1);

assign add_ln292_fu_2175_p2 = (sX_4_load_reg_2611 + 32'd1);

assign and_ln255_5_fu_1213_p2 = (icmp_ln255_9_fu_1201_p2 & icmp_ln255_8_fu_1181_p2);

assign and_ln255_6_fu_1219_p2 = (and_ln255_fu_1207_p2 & and_ln255_5_fu_1213_p2);

assign and_ln255_fu_1207_p2 = (icmp_ln255_fu_1151_p2 & icmp_ln255_7_fu_1161_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_block_state10_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3 = ((icmp_ln247_fu_1130_p2 == 1'd0) & (data_V_V_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_ignore_call0 = ((icmp_ln247_fu_1130_p2 == 1'd0) & (data_V_V_empty_n == 1'b0));
end

assign ap_block_state6_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_623 = (((icmp_ln277_fu_2159_p2 == 1'd0) & (1'd0 == and_ln255_6_reg_2643)) | ((icmp_ln266_fu_2142_p2 == 1'd1) & (icmp_ln277_fu_2159_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_634 = (((icmp_ln277_fu_2159_p2 == 1'd1) & (icmp_ln281_fu_2199_p2 == 1'd0) & (1'd0 == and_ln255_6_reg_2643)) | ((icmp_ln277_fu_2159_p2 == 1'd1) & (icmp_ln266_fu_2142_p2 == 1'd1) & (icmp_ln281_fu_2199_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_781 = (((icmp_ln281_fu_2199_p2 == 1'd1) & (icmp_ln277_fu_2159_p2 == 1'd1) & (1'd0 == and_ln255_6_reg_2643)) | ((icmp_ln281_fu_2199_p2 == 1'd1) & (icmp_ln277_fu_2159_p2 == 1'd1) & (icmp_ln266_fu_2142_p2 == 1'd1)));
end

always @ (*) begin
    ap_condition_839 = (((icmp_ln277_fu_2159_p2 == 1'd1) & (1'd0 == and_ln255_6_reg_2643)) | ((icmp_ln277_fu_2159_p2 == 1'd1) & (icmp_ln266_fu_2142_p2 == 1'd1)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_start = grp_cnnshift_arr_buffer_ap_fixed_ap_fixed_config2_s_fu_1109_ap_start_reg;

assign grp_fu_1656_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2244_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2250_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2256_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2262_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2268_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2274_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2280_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2286_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2292_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2298_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2304_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2310_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2316_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2322_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2328_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2334_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2340_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2346_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2352_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2358_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2364_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2370_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2376_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2382_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2388_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2394_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2400_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2406_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2412_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2418_p1 = sext_ln1116_cast_fu_1557_p1;

assign grp_fu_2424_p1 = sext_ln1116_cast_fu_1557_p1;

assign i1_fu_1136_p2 = (i1_0_i_reg_648 + 2'd1);

assign i_fu_1124_p2 = (i_0_i_reg_637 + 11'd1);

assign i_ic_fu_2148_p2 = (i_ic_0_i_reg_1087 + 6'd1);

assign icmp_ln245_fu_1118_p2 = ((i_0_i_reg_637 == 11'd1156) ? 1'b1 : 1'b0);

assign icmp_ln247_fu_1130_p2 = ((i1_0_i_reg_648 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln255_7_fu_1161_p2 = ((sY_4 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln255_8_fu_1181_p2 = (($signed(tmp_127_fu_1171_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln255_9_fu_1201_p2 = (($signed(tmp_128_fu_1191_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln255_fu_1151_p2 = ((sX_4 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln266_fu_2142_p2 = ((i_ic_0_i_reg_1087 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln277_fu_2159_p2 = ((pX_4_load_reg_2637 == 32'd33) ? 1'b1 : 1'b0);

assign icmp_ln281_fu_2199_p2 = ((pY_4_load_reg_2631 == 32'd33) ? 1'b1 : 1'b0);

assign icmp_ln336_fu_1225_p2 = ((in_index_reg_1076 == 5'd27) ? 1'b1 : 1'b0);

assign ir_fu_1231_p2 = (in_index_reg_1076 + 5'd1);

assign res_V_V_din = res_pack_V_reg_3377;

assign select_ln287_fu_2220_p3 = ((icmp_ln255_7_reg_2626[0:0] === 1'b1) ? 32'd2 : add_ln287_fu_2215_p2);

assign select_ln292_fu_2180_p3 = ((icmp_ln255_reg_2616[0:0] === 1'b1) ? 32'd2 : add_ln292_fu_2175_p2);

assign sext_ln1116_cast_fu_1557_p1 = $signed(layer_in_V_9_load_reg_2666);

assign start_out = real_start;

assign tmp_127_fu_1171_p4 = {{pY_4[31:1]}};

assign tmp_128_fu_1191_p4 = {{pX_4[31:1]}};

assign trunc_ln344_fu_1243_p1 = w2_V_q0[5:0];

assign trunc_ln708_10_fu_1767_p4 = {{mul_ln1118_108_reg_3082[20:5]}};

assign trunc_ln708_11_fu_1776_p4 = {{mul_ln1118_109_reg_3087[20:5]}};

assign trunc_ln708_12_fu_1785_p4 = {{mul_ln1118_110_reg_3092[20:5]}};

assign trunc_ln708_13_fu_1794_p4 = {{mul_ln1118_111_reg_3097[20:5]}};

assign trunc_ln708_14_fu_1803_p4 = {{mul_ln1118_112_reg_3102[20:5]}};

assign trunc_ln708_15_fu_1812_p4 = {{mul_ln1118_113_reg_3107[20:5]}};

assign trunc_ln708_16_fu_1821_p4 = {{mul_ln1118_114_reg_3112[20:5]}};

assign trunc_ln708_17_fu_1830_p4 = {{mul_ln1118_115_reg_3117[20:5]}};

assign trunc_ln708_18_fu_1839_p4 = {{mul_ln1118_116_reg_3122[20:5]}};

assign trunc_ln708_19_fu_1848_p4 = {{mul_ln1118_117_reg_3127[20:5]}};

assign trunc_ln708_1_fu_1686_p4 = {{mul_ln1118_99_reg_3037[20:5]}};

assign trunc_ln708_20_fu_1857_p4 = {{mul_ln1118_118_reg_3132[20:5]}};

assign trunc_ln708_21_fu_1866_p4 = {{mul_ln1118_119_reg_3137[20:5]}};

assign trunc_ln708_22_fu_1875_p4 = {{mul_ln1118_120_reg_3142[20:5]}};

assign trunc_ln708_23_fu_1884_p4 = {{mul_ln1118_121_reg_3147[20:5]}};

assign trunc_ln708_24_fu_1893_p4 = {{mul_ln1118_122_reg_3152[20:5]}};

assign trunc_ln708_25_fu_1902_p4 = {{mul_ln1118_123_reg_3157[20:5]}};

assign trunc_ln708_26_fu_1911_p4 = {{mul_ln1118_124_reg_3162[20:5]}};

assign trunc_ln708_27_fu_1920_p4 = {{mul_ln1118_125_reg_3167[20:5]}};

assign trunc_ln708_28_fu_1929_p4 = {{mul_ln1118_126_reg_3172[20:5]}};

assign trunc_ln708_29_fu_1938_p4 = {{mul_ln1118_127_reg_3177[20:5]}};

assign trunc_ln708_2_fu_1695_p4 = {{mul_ln1118_100_reg_3042[20:5]}};

assign trunc_ln708_30_fu_1947_p4 = {{mul_ln1118_128_reg_3182[20:5]}};

assign trunc_ln708_3_fu_1704_p4 = {{mul_ln1118_101_reg_3047[20:5]}};

assign trunc_ln708_4_fu_1713_p4 = {{mul_ln1118_102_reg_3052[20:5]}};

assign trunc_ln708_5_fu_1722_p4 = {{mul_ln1118_103_reg_3057[20:5]}};

assign trunc_ln708_6_fu_1731_p4 = {{mul_ln1118_104_reg_3062[20:5]}};

assign trunc_ln708_7_fu_1740_p4 = {{mul_ln1118_105_reg_3067[20:5]}};

assign trunc_ln708_8_fu_1749_p4 = {{mul_ln1118_106_reg_3072[20:5]}};

assign trunc_ln708_9_fu_1758_p4 = {{mul_ln1118_107_reg_3077[20:5]}};

assign trunc_ln_fu_1677_p4 = {{mul_ln1118_reg_3032[20:5]}};

assign w2_V_address0 = zext_ln344_fu_1237_p1;

assign zext_ln249_fu_1142_p1 = i1_0_i_reg_648;

assign zext_ln268_fu_2154_p1 = i_ic_0_i_reg_1087;

assign zext_ln344_fu_1237_p1 = in_index_reg_1076;

endmodule //conv_2d_cl_me_ap_fixed_ap_fixed_16_4_5_3_0_config2_s
