// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state1 = "1";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state2 = "10";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state3 = "100";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state4 = "1000";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state5 = "10000";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state6 = "100000";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state7 = "1000000";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state8 = "10000000";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state9 = "100000000";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state10 = "1000000000";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state11 = "10000000000";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state12 = "100000000000";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<24> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_6 = "110";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_16 = "10110";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_1 = "1";
const sc_lv<1> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv1_0 = "0";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_2 = "10";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_3 = "11";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_4 = "100";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_5 = "101";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_7 = "111";
const sc_lv<1> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv1_1 = "1";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_8 = "1000";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_9 = "1001";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_A = "1010";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_D = "1101";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_E = "1110";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_F = "1111";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_10 = "10000";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_11 = "10001";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_13 = "10011";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_14 = "10100";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_15 = "10101";
const sc_lv<6> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv6_0 = "000000";
const sc_lv<2> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv2_1 = "1";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_C = "1100";
const sc_lv<5> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv5_0 = "00000";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_B = "1011";
const sc_lv<2> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv2_0 = "00";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_12 = "10010";
const sc_lv<32> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv32_17 = "10111";
const sc_lv<6> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv6_20 = "100000";
const sc_lv<6> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv6_1 = "1";
const sc_lv<58> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv58_1 = "1";
const sc_lv<2> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv2_3 = "11";
const sc_lv<5> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv5_8 = "1000";
const sc_lv<5> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv5_10 = "10000";
const sc_lv<5> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv5_1 = "1";
const sc_lv<2> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv2_2 = "10";
const sc_lv<7> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv7_20 = "100000";
const sc_lv<7> cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_lv7_0 = "0000000";
const bool cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::ap_const_boolean_1 = true;

cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    linebuffer_V_3_U = new cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s_linebuffeThq("linebuffer_V_3_U");
    linebuffer_V_3_U->clk(ap_clk);
    linebuffer_V_3_U->reset(ap_rst);
    linebuffer_V_3_U->address0(linebuffer_V_3_address0);
    linebuffer_V_3_U->ce0(linebuffer_V_3_ce0);
    linebuffer_V_3_U->we0(linebuffer_V_3_we0);
    linebuffer_V_3_U->d0(linebuffer_V_3_d0);
    linebuffer_V_3_U->q0(linebuffer_V_3_q0);
    tmpinput_V_U = new cnnshift_arr_buffer_ap_fixed_ap_fixed_config5_s_tmpinput_V("tmpinput_V_U");
    tmpinput_V_U->clk(ap_clk);
    tmpinput_V_U->reset(ap_rst);
    tmpinput_V_U->address0(tmpinput_V_address0);
    tmpinput_V_U->ce0(tmpinput_V_ce0);
    tmpinput_V_U->we0(tmpinput_V_we0);
    tmpinput_V_U->d0(tmpinput_V_d0);
    tmpinput_V_U->q0(tmpinput_V_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln126_1_fu_607_p2);
    sensitive << ( sub_ln126_reg_881 );
    sensitive << ( zext_ln126_5_fu_603_p1 );

    SC_METHOD(thread_add_ln126_2_fu_598_p2);
    sensitive << ( zext_ln126_2_reg_863 );
    sensitive << ( zext_ln125_fu_582_p1 );

    SC_METHOD(thread_add_ln126_3_fu_612_p2);
    sensitive << ( add_ln126_reg_868 );
    sensitive << ( zext_ln125_fu_582_p1 );

    SC_METHOD(thread_add_ln126_4_fu_621_p2);
    sensitive << ( sub_ln126_reg_881 );
    sensitive << ( zext_ln126_6_fu_617_p1 );

    SC_METHOD(thread_add_ln126_fu_534_p2);
    sensitive << ( zext_ln126_2_fu_530_p1 );

    SC_METHOD(thread_add_ln134_fu_708_p2);
    sensitive << ( sub_ln134_reg_923 );
    sensitive << ( zext_ln134_2_fu_704_p1 );

    SC_METHOD(thread_add_ln182_fu_337_p2);
    sensitive << ( zext_ln203_1_reg_755 );
    sensitive << ( zext_ln182_fu_333_p1 );

    SC_METHOD(thread_add_ln187_1_fu_360_p2);
    sensitive << ( zext_ln203_1_reg_755 );
    sensitive << ( zext_ln187_1_fu_356_p1 );

    SC_METHOD(thread_add_ln187_fu_342_p2);
    sensitive << ( i1_0_reg_195 );

    SC_METHOD(thread_add_ln203_1_fu_459_p2);
    sensitive << ( zext_ln203_1_reg_755 );
    sensitive << ( zext_ln203_3_fu_455_p1 );

    SC_METHOD(thread_add_ln203_2_fu_419_p2);
    sensitive << ( zext_ln187_reg_791 );
    sensitive << ( zext_ln203_5_fu_415_p1 );

    SC_METHOD(thread_add_ln203_3_fu_477_p2);
    sensitive << ( zext_ln203_reg_748 );
    sensitive << ( tmp_9_cast_fu_470_p3 );

    SC_METHOD(thread_add_ln203_4_fu_436_p2);
    sensitive << ( zext_ln187_reg_791 );
    sensitive << ( zext_ln203_7_fu_432_p1 );

    SC_METHOD(thread_add_ln203_5_fu_489_p2);
    sensitive << ( zext_ln203_reg_748 );
    sensitive << ( tmp_12_cast_fu_482_p3 );

    SC_METHOD(thread_add_ln203_6_fu_717_p2);
    sensitive << ( zext_ln133_reg_928 );
    sensitive << ( zext_ln203_9_fu_713_p1 );

    SC_METHOD(thread_add_ln203_fu_385_p2);
    sensitive << ( zext_ln203_reg_748 );
    sensitive << ( tmp_4_cast_fu_376_p4 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( icmp_ln131_fu_642_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( icmp_ln131_fu_642_p2 );

    SC_METHOD(thread_data_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln179_fu_291_p1 );

    SC_METHOD(thread_data_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_i0_1_fu_512_p2);
    sensitive << ( i0_0_i_reg_218 );

    SC_METHOD(thread_i0_fu_285_p2);
    sensitive << ( i0_0_reg_183 );

    SC_METHOD(thread_i1_1_fu_648_p2);
    sensitive << ( i11_0_i_reg_251 );

    SC_METHOD(thread_i1_2_fu_546_p2);
    sensitive << ( i1_0_i_reg_229 );

    SC_METHOD(thread_i1_fu_464_p2);
    sensitive << ( i1_0_reg_195 );

    SC_METHOD(thread_i2_1_fu_690_p2);
    sensitive << ( i22_0_i_reg_262 );

    SC_METHOD(thread_i2_2_fu_592_p2);
    sensitive << ( i2_0_i_reg_240 );

    SC_METHOD(thread_i2_fu_401_p2);
    sensitive << ( i2_0_reg_207 );

    SC_METHOD(thread_icmp_ln122_fu_506_p2);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( i0_0_i_reg_218 );

    SC_METHOD(thread_icmp_ln124_fu_540_p2);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( i1_0_i_reg_229 );

    SC_METHOD(thread_icmp_ln125_fu_586_p2);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( i2_0_i_reg_240 );

    SC_METHOD(thread_icmp_ln131_fu_642_p2);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( i11_0_i_reg_251 );

    SC_METHOD(thread_icmp_ln133_fu_684_p2);
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( i22_0_i_reg_262 );

    SC_METHOD(thread_icmp_ln177_fu_279_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i0_0_reg_183 );

    SC_METHOD(thread_icmp_ln180_fu_313_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i1_0_reg_195 );

    SC_METHOD(thread_icmp_ln189_fu_395_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( i2_0_reg_207 );

    SC_METHOD(thread_linebuffer_V_3_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( linebuffer_V_3_addr_1_reg_797 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( zext_ln187_2_fu_369_p1 );
    sensitive << ( zext_ln203_8_fu_494_p1 );
    sensitive << ( zext_ln203_6_fu_498_p1 );

    SC_METHOD(thread_linebuffer_V_3_ce0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_linebuffer_V_3_d0);
    sensitive << ( reg_273 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( linebuffer_V_3_load_reg_850 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_linebuffer_V_3_we0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln189_fu_395_p2 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_or_ln_fu_696_p3);
    sensitive << ( i22_0_i_reg_262 );

    SC_METHOD(thread_output_V_address0);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( zext_ln126_1_fu_629_p1 );
    sensitive << ( zext_ln126_fu_637_p1 );
    sensitive << ( zext_ln134_fu_726_p1 );

    SC_METHOD(thread_output_V_ce0);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_output_V_d0);
    sensitive << ( reg_273 );
    sensitive << ( output_V_load_reg_910 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_output_V_we0);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_sext_ln126_1_fu_626_p1);
    sensitive << ( add_ln126_4_reg_900 );

    SC_METHOD(thread_sext_ln126_fu_634_p1);
    sensitive << ( add_ln126_1_reg_895 );

    SC_METHOD(thread_shl_ln126_1_fu_552_p3);
    sensitive << ( i1_0_i_reg_229 );

    SC_METHOD(thread_shl_ln126_2_fu_564_p3);
    sensitive << ( i1_0_i_reg_229 );

    SC_METHOD(thread_shl_ln134_1_fu_662_p3);
    sensitive << ( i11_0_i_reg_251 );

    SC_METHOD(thread_shl_ln1_fu_654_p3);
    sensitive << ( i11_0_i_reg_251 );

    SC_METHOD(thread_shl_ln_fu_522_p3);
    sensitive << ( trunc_ln126_fu_518_p1 );

    SC_METHOD(thread_sub_ln126_fu_576_p2);
    sensitive << ( zext_ln126_3_fu_560_p1 );
    sensitive << ( zext_ln126_4_fu_572_p1 );

    SC_METHOD(thread_sub_ln134_fu_674_p2);
    sensitive << ( shl_ln1_fu_654_p3 );
    sensitive << ( zext_ln134_1_fu_670_p1 );

    SC_METHOD(thread_sub_ln195_fu_441_p2);
    sensitive << ( i1_0_reg_195 );

    SC_METHOD(thread_tmp_10_fu_424_p3);
    sensitive << ( i2_fu_401_p2 );

    SC_METHOD(thread_tmp_12_cast_fu_482_p3);
    sensitive << ( add_ln203_4_reg_820 );

    SC_METHOD(thread_tmp_2_fu_325_p3);
    sensitive << ( xor_ln182_fu_319_p2 );

    SC_METHOD(thread_tmp_3_fu_348_p3);
    sensitive << ( add_ln187_fu_342_p2 );

    SC_METHOD(thread_tmp_4_cast_fu_376_p4);
    sensitive << ( add_ln187_reg_770 );

    SC_METHOD(thread_tmp_6_fu_447_p3);
    sensitive << ( sub_ln195_fu_441_p2 );

    SC_METHOD(thread_tmp_7_fu_407_p3);
    sensitive << ( i2_0_reg_207 );

    SC_METHOD(thread_tmp_9_cast_fu_470_p3);
    sensitive << ( add_ln203_2_reg_815 );

    SC_METHOD(thread_tmp_fu_304_p3);
    sensitive << ( i0_0_reg_183 );

    SC_METHOD(thread_tmpinput_V_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( tmp_fu_304_p3 );
    sensitive << ( zext_ln182_1_fu_365_p1 );
    sensitive << ( zext_ln203_4_fu_502_p1 );
    sensitive << ( zext_ln203_10_fu_722_p1 );

    SC_METHOD(thread_tmpinput_V_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_tmpinput_V_d0);
    sensitive << ( data_V_load_reg_743 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_V_reg_802 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_tmpinput_V_we0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_trunc_ln126_fu_518_p1);
    sensitive << ( i0_0_i_reg_218 );

    SC_METHOD(thread_xor_ln182_fu_319_p2);
    sensitive << ( i1_0_reg_195 );

    SC_METHOD(thread_zext_ln125_fu_582_p1);
    sensitive << ( i2_0_i_reg_240 );

    SC_METHOD(thread_zext_ln126_1_fu_629_p1);
    sensitive << ( sext_ln126_1_fu_626_p1 );

    SC_METHOD(thread_zext_ln126_2_fu_530_p1);
    sensitive << ( shl_ln_fu_522_p3 );

    SC_METHOD(thread_zext_ln126_3_fu_560_p1);
    sensitive << ( shl_ln126_1_fu_552_p3 );

    SC_METHOD(thread_zext_ln126_4_fu_572_p1);
    sensitive << ( shl_ln126_2_fu_564_p3 );

    SC_METHOD(thread_zext_ln126_5_fu_603_p1);
    sensitive << ( add_ln126_2_fu_598_p2 );

    SC_METHOD(thread_zext_ln126_6_fu_617_p1);
    sensitive << ( add_ln126_3_fu_612_p2 );

    SC_METHOD(thread_zext_ln126_fu_637_p1);
    sensitive << ( sext_ln126_fu_634_p1 );

    SC_METHOD(thread_zext_ln133_fu_680_p1);
    sensitive << ( shl_ln134_1_fu_662_p3 );

    SC_METHOD(thread_zext_ln134_1_fu_670_p1);
    sensitive << ( shl_ln134_1_fu_662_p3 );

    SC_METHOD(thread_zext_ln134_2_fu_704_p1);
    sensitive << ( or_ln_fu_696_p3 );

    SC_METHOD(thread_zext_ln134_fu_726_p1);
    sensitive << ( add_ln134_reg_941 );

    SC_METHOD(thread_zext_ln179_fu_291_p1);
    sensitive << ( i0_0_reg_183 );

    SC_METHOD(thread_zext_ln182_1_fu_365_p1);
    sensitive << ( add_ln182_reg_765 );

    SC_METHOD(thread_zext_ln182_fu_333_p1);
    sensitive << ( tmp_2_fu_325_p3 );

    SC_METHOD(thread_zext_ln187_1_fu_356_p1);
    sensitive << ( tmp_3_fu_348_p3 );

    SC_METHOD(thread_zext_ln187_2_fu_369_p1);
    sensitive << ( add_ln187_1_reg_776 );

    SC_METHOD(thread_zext_ln187_fu_373_p1);
    sensitive << ( add_ln187_reg_770 );

    SC_METHOD(thread_zext_ln203_10_fu_722_p1);
    sensitive << ( add_ln203_6_reg_946 );

    SC_METHOD(thread_zext_ln203_1_fu_300_p1);
    sensitive << ( i0_0_reg_183 );

    SC_METHOD(thread_zext_ln203_2_fu_390_p1);
    sensitive << ( add_ln203_fu_385_p2 );

    SC_METHOD(thread_zext_ln203_3_fu_455_p1);
    sensitive << ( tmp_6_fu_447_p3 );

    SC_METHOD(thread_zext_ln203_4_fu_502_p1);
    sensitive << ( add_ln203_1_reg_825 );

    SC_METHOD(thread_zext_ln203_5_fu_415_p1);
    sensitive << ( tmp_7_fu_407_p3 );

    SC_METHOD(thread_zext_ln203_6_fu_498_p1);
    sensitive << ( add_ln203_3_reg_835 );

    SC_METHOD(thread_zext_ln203_7_fu_432_p1);
    sensitive << ( tmp_10_fu_424_p3 );

    SC_METHOD(thread_zext_ln203_8_fu_494_p1);
    sensitive << ( add_ln203_5_reg_840 );

    SC_METHOD(thread_zext_ln203_9_fu_713_p1);
    sensitive << ( i22_0_i_reg_262 );

    SC_METHOD(thread_zext_ln203_fu_296_p1);
    sensitive << ( i0_0_reg_183 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln177_fu_279_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln180_fu_313_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln189_fu_395_p2 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( icmp_ln122_fu_506_p2 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( icmp_ln124_fu_540_p2 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( icmp_ln125_fu_586_p2 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( icmp_ln131_fu_642_p2 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( icmp_ln133_fu_684_p2 );

    ap_CS_fsm = "000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_V_address0, "(port)data_V_address0");
    sc_trace(mVcdFile, data_V_ce0, "(port)data_V_ce0");
    sc_trace(mVcdFile, data_V_q0, "(port)data_V_q0");
    sc_trace(mVcdFile, output_V_address0, "(port)output_V_address0");
    sc_trace(mVcdFile, output_V_ce0, "(port)output_V_ce0");
    sc_trace(mVcdFile, output_V_we0, "(port)output_V_we0");
    sc_trace(mVcdFile, output_V_d0, "(port)output_V_d0");
    sc_trace(mVcdFile, output_V_q0, "(port)output_V_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, linebuffer_V_3_address0, "linebuffer_V_3_address0");
    sc_trace(mVcdFile, linebuffer_V_3_ce0, "linebuffer_V_3_ce0");
    sc_trace(mVcdFile, linebuffer_V_3_we0, "linebuffer_V_3_we0");
    sc_trace(mVcdFile, linebuffer_V_3_d0, "linebuffer_V_3_d0");
    sc_trace(mVcdFile, linebuffer_V_3_q0, "linebuffer_V_3_q0");
    sc_trace(mVcdFile, tmpinput_V_q0, "tmpinput_V_q0");
    sc_trace(mVcdFile, reg_273, "reg_273");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, i0_fu_285_p2, "i0_fu_285_p2");
    sc_trace(mVcdFile, i0_reg_733, "i0_reg_733");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln177_fu_279_p2, "icmp_ln177_fu_279_p2");
    sc_trace(mVcdFile, data_V_load_reg_743, "data_V_load_reg_743");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, zext_ln203_fu_296_p1, "zext_ln203_fu_296_p1");
    sc_trace(mVcdFile, zext_ln203_reg_748, "zext_ln203_reg_748");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, zext_ln203_1_fu_300_p1, "zext_ln203_1_fu_300_p1");
    sc_trace(mVcdFile, zext_ln203_1_reg_755, "zext_ln203_1_reg_755");
    sc_trace(mVcdFile, add_ln182_fu_337_p2, "add_ln182_fu_337_p2");
    sc_trace(mVcdFile, add_ln182_reg_765, "add_ln182_reg_765");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, icmp_ln180_fu_313_p2, "icmp_ln180_fu_313_p2");
    sc_trace(mVcdFile, add_ln187_fu_342_p2, "add_ln187_fu_342_p2");
    sc_trace(mVcdFile, add_ln187_reg_770, "add_ln187_reg_770");
    sc_trace(mVcdFile, add_ln187_1_fu_360_p2, "add_ln187_1_fu_360_p2");
    sc_trace(mVcdFile, add_ln187_1_reg_776, "add_ln187_1_reg_776");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, zext_ln187_fu_373_p1, "zext_ln187_fu_373_p1");
    sc_trace(mVcdFile, zext_ln187_reg_791, "zext_ln187_reg_791");
    sc_trace(mVcdFile, linebuffer_V_3_addr_1_reg_797, "linebuffer_V_3_addr_1_reg_797");
    sc_trace(mVcdFile, tmp_V_reg_802, "tmp_V_reg_802");
    sc_trace(mVcdFile, i2_fu_401_p2, "i2_fu_401_p2");
    sc_trace(mVcdFile, i2_reg_810, "i2_reg_810");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, add_ln203_2_fu_419_p2, "add_ln203_2_fu_419_p2");
    sc_trace(mVcdFile, add_ln203_2_reg_815, "add_ln203_2_reg_815");
    sc_trace(mVcdFile, icmp_ln189_fu_395_p2, "icmp_ln189_fu_395_p2");
    sc_trace(mVcdFile, add_ln203_4_fu_436_p2, "add_ln203_4_fu_436_p2");
    sc_trace(mVcdFile, add_ln203_4_reg_820, "add_ln203_4_reg_820");
    sc_trace(mVcdFile, add_ln203_1_fu_459_p2, "add_ln203_1_fu_459_p2");
    sc_trace(mVcdFile, add_ln203_1_reg_825, "add_ln203_1_reg_825");
    sc_trace(mVcdFile, i1_fu_464_p2, "i1_fu_464_p2");
    sc_trace(mVcdFile, i1_reg_830, "i1_reg_830");
    sc_trace(mVcdFile, add_ln203_3_fu_477_p2, "add_ln203_3_fu_477_p2");
    sc_trace(mVcdFile, add_ln203_3_reg_835, "add_ln203_3_reg_835");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, add_ln203_5_fu_489_p2, "add_ln203_5_fu_489_p2");
    sc_trace(mVcdFile, add_ln203_5_reg_840, "add_ln203_5_reg_840");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, linebuffer_V_3_load_reg_850, "linebuffer_V_3_load_reg_850");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, i0_1_fu_512_p2, "i0_1_fu_512_p2");
    sc_trace(mVcdFile, i0_1_reg_858, "i0_1_reg_858");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, zext_ln126_2_fu_530_p1, "zext_ln126_2_fu_530_p1");
    sc_trace(mVcdFile, zext_ln126_2_reg_863, "zext_ln126_2_reg_863");
    sc_trace(mVcdFile, icmp_ln122_fu_506_p2, "icmp_ln122_fu_506_p2");
    sc_trace(mVcdFile, add_ln126_fu_534_p2, "add_ln126_fu_534_p2");
    sc_trace(mVcdFile, add_ln126_reg_868, "add_ln126_reg_868");
    sc_trace(mVcdFile, i1_2_fu_546_p2, "i1_2_fu_546_p2");
    sc_trace(mVcdFile, i1_2_reg_876, "i1_2_reg_876");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, sub_ln126_fu_576_p2, "sub_ln126_fu_576_p2");
    sc_trace(mVcdFile, sub_ln126_reg_881, "sub_ln126_reg_881");
    sc_trace(mVcdFile, icmp_ln124_fu_540_p2, "icmp_ln124_fu_540_p2");
    sc_trace(mVcdFile, i2_2_fu_592_p2, "i2_2_fu_592_p2");
    sc_trace(mVcdFile, i2_2_reg_890, "i2_2_reg_890");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, add_ln126_1_fu_607_p2, "add_ln126_1_fu_607_p2");
    sc_trace(mVcdFile, add_ln126_1_reg_895, "add_ln126_1_reg_895");
    sc_trace(mVcdFile, icmp_ln125_fu_586_p2, "icmp_ln125_fu_586_p2");
    sc_trace(mVcdFile, add_ln126_4_fu_621_p2, "add_ln126_4_fu_621_p2");
    sc_trace(mVcdFile, add_ln126_4_reg_900, "add_ln126_4_reg_900");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, output_V_load_reg_910, "output_V_load_reg_910");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, i1_1_fu_648_p2, "i1_1_fu_648_p2");
    sc_trace(mVcdFile, i1_1_reg_918, "i1_1_reg_918");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, sub_ln134_fu_674_p2, "sub_ln134_fu_674_p2");
    sc_trace(mVcdFile, sub_ln134_reg_923, "sub_ln134_reg_923");
    sc_trace(mVcdFile, icmp_ln131_fu_642_p2, "icmp_ln131_fu_642_p2");
    sc_trace(mVcdFile, zext_ln133_fu_680_p1, "zext_ln133_fu_680_p1");
    sc_trace(mVcdFile, zext_ln133_reg_928, "zext_ln133_reg_928");
    sc_trace(mVcdFile, i2_1_fu_690_p2, "i2_1_fu_690_p2");
    sc_trace(mVcdFile, i2_1_reg_936, "i2_1_reg_936");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, add_ln134_fu_708_p2, "add_ln134_fu_708_p2");
    sc_trace(mVcdFile, add_ln134_reg_941, "add_ln134_reg_941");
    sc_trace(mVcdFile, icmp_ln133_fu_684_p2, "icmp_ln133_fu_684_p2");
    sc_trace(mVcdFile, add_ln203_6_fu_717_p2, "add_ln203_6_fu_717_p2");
    sc_trace(mVcdFile, add_ln203_6_reg_946, "add_ln203_6_reg_946");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, tmpinput_V_address0, "tmpinput_V_address0");
    sc_trace(mVcdFile, tmpinput_V_ce0, "tmpinput_V_ce0");
    sc_trace(mVcdFile, tmpinput_V_we0, "tmpinput_V_we0");
    sc_trace(mVcdFile, tmpinput_V_d0, "tmpinput_V_d0");
    sc_trace(mVcdFile, i0_0_reg_183, "i0_0_reg_183");
    sc_trace(mVcdFile, i1_0_reg_195, "i1_0_reg_195");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, i2_0_reg_207, "i2_0_reg_207");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, i0_0_i_reg_218, "i0_0_i_reg_218");
    sc_trace(mVcdFile, i1_0_i_reg_229, "i1_0_i_reg_229");
    sc_trace(mVcdFile, i2_0_i_reg_240, "i2_0_i_reg_240");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, i11_0_i_reg_251, "i11_0_i_reg_251");
    sc_trace(mVcdFile, i22_0_i_reg_262, "i22_0_i_reg_262");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, zext_ln179_fu_291_p1, "zext_ln179_fu_291_p1");
    sc_trace(mVcdFile, tmp_fu_304_p3, "tmp_fu_304_p3");
    sc_trace(mVcdFile, zext_ln182_1_fu_365_p1, "zext_ln182_1_fu_365_p1");
    sc_trace(mVcdFile, zext_ln187_2_fu_369_p1, "zext_ln187_2_fu_369_p1");
    sc_trace(mVcdFile, zext_ln203_2_fu_390_p1, "zext_ln203_2_fu_390_p1");
    sc_trace(mVcdFile, zext_ln203_8_fu_494_p1, "zext_ln203_8_fu_494_p1");
    sc_trace(mVcdFile, zext_ln203_6_fu_498_p1, "zext_ln203_6_fu_498_p1");
    sc_trace(mVcdFile, zext_ln203_4_fu_502_p1, "zext_ln203_4_fu_502_p1");
    sc_trace(mVcdFile, zext_ln126_1_fu_629_p1, "zext_ln126_1_fu_629_p1");
    sc_trace(mVcdFile, zext_ln126_fu_637_p1, "zext_ln126_fu_637_p1");
    sc_trace(mVcdFile, zext_ln203_10_fu_722_p1, "zext_ln203_10_fu_722_p1");
    sc_trace(mVcdFile, zext_ln134_fu_726_p1, "zext_ln134_fu_726_p1");
    sc_trace(mVcdFile, xor_ln182_fu_319_p2, "xor_ln182_fu_319_p2");
    sc_trace(mVcdFile, tmp_2_fu_325_p3, "tmp_2_fu_325_p3");
    sc_trace(mVcdFile, zext_ln182_fu_333_p1, "zext_ln182_fu_333_p1");
    sc_trace(mVcdFile, tmp_3_fu_348_p3, "tmp_3_fu_348_p3");
    sc_trace(mVcdFile, zext_ln187_1_fu_356_p1, "zext_ln187_1_fu_356_p1");
    sc_trace(mVcdFile, tmp_4_cast_fu_376_p4, "tmp_4_cast_fu_376_p4");
    sc_trace(mVcdFile, add_ln203_fu_385_p2, "add_ln203_fu_385_p2");
    sc_trace(mVcdFile, tmp_7_fu_407_p3, "tmp_7_fu_407_p3");
    sc_trace(mVcdFile, zext_ln203_5_fu_415_p1, "zext_ln203_5_fu_415_p1");
    sc_trace(mVcdFile, tmp_10_fu_424_p3, "tmp_10_fu_424_p3");
    sc_trace(mVcdFile, zext_ln203_7_fu_432_p1, "zext_ln203_7_fu_432_p1");
    sc_trace(mVcdFile, sub_ln195_fu_441_p2, "sub_ln195_fu_441_p2");
    sc_trace(mVcdFile, tmp_6_fu_447_p3, "tmp_6_fu_447_p3");
    sc_trace(mVcdFile, zext_ln203_3_fu_455_p1, "zext_ln203_3_fu_455_p1");
    sc_trace(mVcdFile, tmp_9_cast_fu_470_p3, "tmp_9_cast_fu_470_p3");
    sc_trace(mVcdFile, tmp_12_cast_fu_482_p3, "tmp_12_cast_fu_482_p3");
    sc_trace(mVcdFile, trunc_ln126_fu_518_p1, "trunc_ln126_fu_518_p1");
    sc_trace(mVcdFile, shl_ln_fu_522_p3, "shl_ln_fu_522_p3");
    sc_trace(mVcdFile, shl_ln126_1_fu_552_p3, "shl_ln126_1_fu_552_p3");
    sc_trace(mVcdFile, shl_ln126_2_fu_564_p3, "shl_ln126_2_fu_564_p3");
    sc_trace(mVcdFile, zext_ln126_3_fu_560_p1, "zext_ln126_3_fu_560_p1");
    sc_trace(mVcdFile, zext_ln126_4_fu_572_p1, "zext_ln126_4_fu_572_p1");
    sc_trace(mVcdFile, zext_ln125_fu_582_p1, "zext_ln125_fu_582_p1");
    sc_trace(mVcdFile, add_ln126_2_fu_598_p2, "add_ln126_2_fu_598_p2");
    sc_trace(mVcdFile, zext_ln126_5_fu_603_p1, "zext_ln126_5_fu_603_p1");
    sc_trace(mVcdFile, add_ln126_3_fu_612_p2, "add_ln126_3_fu_612_p2");
    sc_trace(mVcdFile, zext_ln126_6_fu_617_p1, "zext_ln126_6_fu_617_p1");
    sc_trace(mVcdFile, sext_ln126_1_fu_626_p1, "sext_ln126_1_fu_626_p1");
    sc_trace(mVcdFile, sext_ln126_fu_634_p1, "sext_ln126_fu_634_p1");
    sc_trace(mVcdFile, shl_ln134_1_fu_662_p3, "shl_ln134_1_fu_662_p3");
    sc_trace(mVcdFile, shl_ln1_fu_654_p3, "shl_ln1_fu_654_p3");
    sc_trace(mVcdFile, zext_ln134_1_fu_670_p1, "zext_ln134_1_fu_670_p1");
    sc_trace(mVcdFile, or_ln_fu_696_p3, "or_ln_fu_696_p3");
    sc_trace(mVcdFile, zext_ln134_2_fu_704_p1, "zext_ln134_2_fu_704_p1");
    sc_trace(mVcdFile, zext_ln203_9_fu_713_p1, "zext_ln203_9_fu_713_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::~cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete linebuffer_V_3_U;
    delete tmpinput_V_U;
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln177_fu_279_p2.read(), ap_const_lv1_1))) {
        i0_0_i_reg_218 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln124_fu_540_p2.read()))) {
        i0_0_i_reg_218 = i0_1_reg_858.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln180_fu_313_p2.read(), ap_const_lv1_1))) {
        i0_0_reg_183 = i0_reg_733.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i0_0_reg_183 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln122_fu_506_p2.read()))) {
        i11_0_i_reg_251 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln133_fu_684_p2.read()))) {
        i11_0_i_reg_251 = i1_1_reg_918.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln125_fu_586_p2.read()))) {
        i1_0_i_reg_229 = i1_2_reg_876.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln122_fu_506_p2.read()))) {
        i1_0_i_reg_229 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        i1_0_reg_195 = i1_reg_830.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i1_0_reg_195 = ap_const_lv2_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln131_fu_642_p2.read()))) {
        i22_0_i_reg_262 = ap_const_lv6_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        i22_0_i_reg_262 = i2_1_reg_936.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln124_fu_540_p2.read()))) {
        i2_0_i_reg_240 = ap_const_lv6_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        i2_0_i_reg_240 = i2_2_reg_890.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        i2_0_reg_207 = i2_reg_810.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        i2_0_reg_207 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln125_fu_586_p2.read()))) {
        add_ln126_1_reg_895 = add_ln126_1_fu_607_p2.read();
        add_ln126_4_reg_900 = add_ln126_4_fu_621_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln122_fu_506_p2.read()))) {
        add_ln126_reg_868 = add_ln126_fu_534_p2.read();
        zext_ln126_2_reg_863 = zext_ln126_2_fu_530_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln133_fu_684_p2.read()))) {
        add_ln134_reg_941 = add_ln134_fu_708_p2.read();
        add_ln203_6_reg_946 = add_ln203_6_fu_717_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln180_fu_313_p2.read()))) {
        add_ln182_reg_765 = add_ln182_fu_337_p2.read();
        add_ln187_1_reg_776 = add_ln187_1_fu_360_p2.read();
        add_ln187_reg_770 = add_ln187_fu_342_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(icmp_ln189_fu_395_p2.read(), ap_const_lv1_1))) {
        add_ln203_1_reg_825 = add_ln203_1_fu_459_p2.read();
        i1_reg_830 = i1_fu_464_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln189_fu_395_p2.read()))) {
        add_ln203_2_reg_815 = add_ln203_2_fu_419_p2.read();
        add_ln203_4_reg_820 = add_ln203_4_fu_436_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        add_ln203_3_reg_835 = add_ln203_3_fu_477_p2.read();
        add_ln203_5_reg_840 = add_ln203_5_fu_489_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        data_V_load_reg_743 = data_V_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        i0_1_reg_858 = i0_1_fu_512_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i0_reg_733 = i0_fu_285_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        i1_1_reg_918 = i1_1_fu_648_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        i1_2_reg_876 = i1_2_fu_546_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        i2_1_reg_936 = i2_1_fu_690_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        i2_2_reg_890 = i2_2_fu_592_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        i2_reg_810 = i2_fu_401_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        linebuffer_V_3_addr_1_reg_797 =  (sc_lv<11>) (zext_ln203_2_fu_390_p1.read());
        tmp_V_reg_802 = linebuffer_V_3_q0.read();
        zext_ln187_reg_791 = zext_ln187_fu_373_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        linebuffer_V_3_load_reg_850 = linebuffer_V_3_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        output_V_load_reg_910 = output_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()))) {
        reg_273 = tmpinput_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln124_fu_540_p2.read()))) {
        sub_ln126_reg_881 = sub_ln126_fu_576_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln131_fu_642_p2.read()))) {
        sub_ln134_reg_923 = sub_ln134_fu_674_p2.read();
        zext_ln133_reg_928 = zext_ln133_fu_680_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        zext_ln203_1_reg_755 = zext_ln203_1_fu_300_p1.read();
        zext_ln203_reg_748 = zext_ln203_fu_296_p1.read();
    }
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_add_ln126_1_fu_607_p2() {
    add_ln126_1_fu_607_p2 = (!zext_ln126_5_fu_603_p1.read().is_01() || !sub_ln126_reg_881.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln126_5_fu_603_p1.read()) + sc_biguint<10>(sub_ln126_reg_881.read()));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_add_ln126_2_fu_598_p2() {
    add_ln126_2_fu_598_p2 = (!zext_ln126_2_reg_863.read().is_01() || !zext_ln125_fu_582_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(zext_ln126_2_reg_863.read()) + sc_biguint<7>(zext_ln125_fu_582_p1.read()));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_add_ln126_3_fu_612_p2() {
    add_ln126_3_fu_612_p2 = (!add_ln126_reg_868.read().is_01() || !zext_ln125_fu_582_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(add_ln126_reg_868.read()) + sc_biguint<7>(zext_ln125_fu_582_p1.read()));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_add_ln126_4_fu_621_p2() {
    add_ln126_4_fu_621_p2 = (!zext_ln126_6_fu_617_p1.read().is_01() || !sub_ln126_reg_881.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln126_6_fu_617_p1.read()) + sc_biguint<10>(sub_ln126_reg_881.read()));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_add_ln126_fu_534_p2() {
    add_ln126_fu_534_p2 = (!ap_const_lv7_20.is_01() || !zext_ln126_2_fu_530_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_20) + sc_biguint<7>(zext_ln126_2_fu_530_p1.read()));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_add_ln134_fu_708_p2() {
    add_ln134_fu_708_p2 = (!sub_ln134_reg_923.read().is_01() || !zext_ln134_2_fu_704_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(sub_ln134_reg_923.read()) + sc_biguint<9>(zext_ln134_2_fu_704_p1.read()));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_add_ln182_fu_337_p2() {
    add_ln182_fu_337_p2 = (!zext_ln182_fu_333_p1.read().is_01() || !zext_ln203_1_reg_755.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln182_fu_333_p1.read()) + sc_biguint<8>(zext_ln203_1_reg_755.read()));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_add_ln187_1_fu_360_p2() {
    add_ln187_1_fu_360_p2 = (!zext_ln187_1_fu_356_p1.read().is_01() || !zext_ln203_1_reg_755.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln187_1_fu_356_p1.read()) + sc_biguint<8>(zext_ln203_1_reg_755.read()));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_add_ln187_fu_342_p2() {
    add_ln187_fu_342_p2 = (!i1_0_reg_195.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<2>(): (sc_biguint<2>(i1_0_reg_195.read()) + sc_bigint<2>(ap_const_lv2_3));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_add_ln203_1_fu_459_p2() {
    add_ln203_1_fu_459_p2 = (!zext_ln203_1_reg_755.read().is_01() || !zext_ln203_3_fu_455_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln203_1_reg_755.read()) + sc_biguint<8>(zext_ln203_3_fu_455_p1.read()));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_add_ln203_2_fu_419_p2() {
    add_ln203_2_fu_419_p2 = (!zext_ln187_reg_791.read().is_01() || !zext_ln203_5_fu_415_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(zext_ln187_reg_791.read()) + sc_biguint<7>(zext_ln203_5_fu_415_p1.read()));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_add_ln203_3_fu_477_p2() {
    add_ln203_3_fu_477_p2 = (!zext_ln203_reg_748.read().is_01() || !tmp_9_cast_fu_470_p3.read().is_01())? sc_lv<12>(): (sc_biguint<12>(zext_ln203_reg_748.read()) + sc_biguint<12>(tmp_9_cast_fu_470_p3.read()));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_add_ln203_4_fu_436_p2() {
    add_ln203_4_fu_436_p2 = (!zext_ln187_reg_791.read().is_01() || !zext_ln203_7_fu_432_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(zext_ln187_reg_791.read()) + sc_biguint<7>(zext_ln203_7_fu_432_p1.read()));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_add_ln203_5_fu_489_p2() {
    add_ln203_5_fu_489_p2 = (!zext_ln203_reg_748.read().is_01() || !tmp_12_cast_fu_482_p3.read().is_01())? sc_lv<12>(): (sc_biguint<12>(zext_ln203_reg_748.read()) + sc_biguint<12>(tmp_12_cast_fu_482_p3.read()));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_add_ln203_6_fu_717_p2() {
    add_ln203_6_fu_717_p2 = (!zext_ln133_reg_928.read().is_01() || !zext_ln203_9_fu_713_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln133_reg_928.read()) + sc_biguint<8>(zext_ln203_9_fu_713_p1.read()));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_add_ln203_fu_385_p2() {
    add_ln203_fu_385_p2 = (!tmp_4_cast_fu_376_p4.read().is_01() || !zext_ln203_reg_748.read().is_01())? sc_lv<12>(): (sc_biguint<12>(tmp_4_cast_fu_376_p4.read()) + sc_biguint<12>(zext_ln203_reg_748.read()));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[21];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln131_fu_642_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln131_fu_642_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_data_V_address0() {
    data_V_address0 =  (sc_lv<5>) (zext_ln179_fu_291_p1.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_data_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_V_ce0 = ap_const_logic_1;
    } else {
        data_V_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_i0_1_fu_512_p2() {
    i0_1_fu_512_p2 = (!i0_0_i_reg_218.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i0_0_i_reg_218.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_i0_fu_285_p2() {
    i0_fu_285_p2 = (!i0_0_reg_183.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(i0_0_reg_183.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_i1_1_fu_648_p2() {
    i1_1_fu_648_p2 = (!i11_0_i_reg_251.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i11_0_i_reg_251.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_i1_2_fu_546_p2() {
    i1_2_fu_546_p2 = (!i1_0_i_reg_229.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i1_0_i_reg_229.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_i1_fu_464_p2() {
    i1_fu_464_p2 = (!i1_0_reg_195.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i1_0_reg_195.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_i2_1_fu_690_p2() {
    i2_1_fu_690_p2 = (!i22_0_i_reg_262.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(i22_0_i_reg_262.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_i2_2_fu_592_p2() {
    i2_2_fu_592_p2 = (!i2_0_i_reg_240.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(i2_0_i_reg_240.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_i2_fu_401_p2() {
    i2_fu_401_p2 = (!i2_0_reg_207.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i2_0_reg_207.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_icmp_ln122_fu_506_p2() {
    icmp_ln122_fu_506_p2 = (!i0_0_i_reg_218.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(i0_0_i_reg_218.read() == ap_const_lv2_2);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_icmp_ln124_fu_540_p2() {
    icmp_ln124_fu_540_p2 = (!i1_0_i_reg_229.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i1_0_i_reg_229.read() == ap_const_lv2_3);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_icmp_ln125_fu_586_p2() {
    icmp_ln125_fu_586_p2 = (!i2_0_i_reg_240.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(i2_0_i_reg_240.read() == ap_const_lv6_20);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_icmp_ln131_fu_642_p2() {
    icmp_ln131_fu_642_p2 = (!i11_0_i_reg_251.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i11_0_i_reg_251.read() == ap_const_lv2_3);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_icmp_ln133_fu_684_p2() {
    icmp_ln133_fu_684_p2 = (!i22_0_i_reg_262.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(i22_0_i_reg_262.read() == ap_const_lv6_20);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_icmp_ln177_fu_279_p2() {
    icmp_ln177_fu_279_p2 = (!i0_0_reg_183.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(i0_0_reg_183.read() == ap_const_lv6_20);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_icmp_ln180_fu_313_p2() {
    icmp_ln180_fu_313_p2 = (!i1_0_reg_195.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i1_0_reg_195.read() == ap_const_lv2_3);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_icmp_ln189_fu_395_p2() {
    icmp_ln189_fu_395_p2 = (!i2_0_reg_207.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(i2_0_reg_207.read() == ap_const_lv5_10);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_linebuffer_V_3_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        linebuffer_V_3_address0 =  (sc_lv<11>) (zext_ln203_6_fu_498_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        linebuffer_V_3_address0 =  (sc_lv<11>) (zext_ln203_8_fu_494_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        linebuffer_V_3_address0 = linebuffer_V_3_addr_1_reg_797.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        linebuffer_V_3_address0 =  (sc_lv<11>) (zext_ln187_2_fu_369_p1.read());
    } else {
        linebuffer_V_3_address0 = "XXXXXXXXXXX";
    }
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_linebuffer_V_3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        linebuffer_V_3_ce0 = ap_const_logic_1;
    } else {
        linebuffer_V_3_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_linebuffer_V_3_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        linebuffer_V_3_d0 = linebuffer_V_3_load_reg_850.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        linebuffer_V_3_d0 = reg_273.read();
    } else {
        linebuffer_V_3_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_linebuffer_V_3_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(icmp_ln189_fu_395_p2.read(), ap_const_lv1_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        linebuffer_V_3_we0 = ap_const_logic_1;
    } else {
        linebuffer_V_3_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_or_ln_fu_696_p3() {
    or_ln_fu_696_p3 = esl_concat<1,6>(ap_const_lv1_1, i22_0_i_reg_262.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_output_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        output_V_address0 =  (sc_lv<9>) (zext_ln134_fu_726_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        output_V_address0 =  (sc_lv<9>) (zext_ln126_fu_637_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        output_V_address0 =  (sc_lv<9>) (zext_ln126_1_fu_629_p1.read());
    } else {
        output_V_address0 =  (sc_lv<9>) ("XXXXXXXXX");
    }
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_output_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()))) {
        output_V_ce0 = ap_const_logic_1;
    } else {
        output_V_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_output_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        output_V_d0 = reg_273.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        output_V_d0 = output_V_load_reg_910.read();
    } else {
        output_V_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_output_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()))) {
        output_V_we0 = ap_const_logic_1;
    } else {
        output_V_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_sext_ln126_1_fu_626_p1() {
    sext_ln126_1_fu_626_p1 = esl_sext<32,10>(add_ln126_4_reg_900.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_sext_ln126_fu_634_p1() {
    sext_ln126_fu_634_p1 = esl_sext<32,10>(add_ln126_1_reg_895.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_shl_ln126_1_fu_552_p3() {
    shl_ln126_1_fu_552_p3 = esl_concat<2,7>(i1_0_i_reg_229.read(), ap_const_lv7_0);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_shl_ln126_2_fu_564_p3() {
    shl_ln126_2_fu_564_p3 = esl_concat<2,5>(i1_0_i_reg_229.read(), ap_const_lv5_0);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_shl_ln134_1_fu_662_p3() {
    shl_ln134_1_fu_662_p3 = esl_concat<2,5>(i11_0_i_reg_251.read(), ap_const_lv5_0);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_shl_ln1_fu_654_p3() {
    shl_ln1_fu_654_p3 = esl_concat<2,7>(i11_0_i_reg_251.read(), ap_const_lv7_0);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_shl_ln_fu_522_p3() {
    shl_ln_fu_522_p3 = esl_concat<1,5>(trunc_ln126_fu_518_p1.read(), ap_const_lv5_0);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_sub_ln126_fu_576_p2() {
    sub_ln126_fu_576_p2 = (!zext_ln126_3_fu_560_p1.read().is_01() || !zext_ln126_4_fu_572_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln126_3_fu_560_p1.read()) - sc_biguint<10>(zext_ln126_4_fu_572_p1.read()));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_sub_ln134_fu_674_p2() {
    sub_ln134_fu_674_p2 = (!shl_ln1_fu_654_p3.read().is_01() || !zext_ln134_1_fu_670_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(shl_ln1_fu_654_p3.read()) - sc_biguint<9>(zext_ln134_1_fu_670_p1.read()));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_sub_ln195_fu_441_p2() {
    sub_ln195_fu_441_p2 = (!ap_const_lv2_2.is_01() || !i1_0_reg_195.read().is_01())? sc_lv<2>(): (sc_bigint<2>(ap_const_lv2_2) - sc_biguint<2>(i1_0_reg_195.read()));
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_tmp_10_fu_424_p3() {
    tmp_10_fu_424_p3 = esl_concat<5,1>(i2_fu_401_p2.read(), ap_const_lv1_0);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_tmp_12_cast_fu_482_p3() {
    tmp_12_cast_fu_482_p3 = esl_concat<7,5>(add_ln203_4_reg_820.read(), ap_const_lv5_0);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_tmp_2_fu_325_p3() {
    tmp_2_fu_325_p3 = esl_concat<2,5>(xor_ln182_fu_319_p2.read(), ap_const_lv5_0);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_tmp_3_fu_348_p3() {
    tmp_3_fu_348_p3 = esl_concat<2,5>(add_ln187_fu_342_p2.read(), ap_const_lv5_0);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_tmp_4_cast_fu_376_p4() {
    tmp_4_cast_fu_376_p4 = esl_concat<7,5>(esl_concat<5,2>(ap_const_lv5_8, add_ln187_reg_770.read()), ap_const_lv5_0);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_tmp_6_fu_447_p3() {
    tmp_6_fu_447_p3 = esl_concat<2,5>(sub_ln195_fu_441_p2.read(), ap_const_lv5_0);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_tmp_7_fu_407_p3() {
    tmp_7_fu_407_p3 = esl_concat<5,1>(i2_0_reg_207.read(), ap_const_lv1_0);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_tmp_9_cast_fu_470_p3() {
    tmp_9_cast_fu_470_p3 = esl_concat<7,5>(add_ln203_2_reg_815.read(), ap_const_lv5_0);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_tmp_fu_304_p3() {
    tmp_fu_304_p3 = esl_concat<58,6>(ap_const_lv58_1, i0_0_reg_183.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_tmpinput_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        tmpinput_V_address0 =  (sc_lv<7>) (zext_ln203_10_fu_722_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        tmpinput_V_address0 =  (sc_lv<7>) (zext_ln203_4_fu_502_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        tmpinput_V_address0 =  (sc_lv<7>) (zext_ln182_1_fu_365_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        tmpinput_V_address0 =  (sc_lv<7>) (tmp_fu_304_p3.read());
    } else {
        tmpinput_V_address0 =  (sc_lv<7>) ("XXXXXXX");
    }
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_tmpinput_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        tmpinput_V_ce0 = ap_const_logic_1;
    } else {
        tmpinput_V_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_tmpinput_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        tmpinput_V_d0 = tmp_V_reg_802.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        tmpinput_V_d0 = data_V_load_reg_743.read();
    } else {
        tmpinput_V_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_tmpinput_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        tmpinput_V_we0 = ap_const_logic_1;
    } else {
        tmpinput_V_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_trunc_ln126_fu_518_p1() {
    trunc_ln126_fu_518_p1 = i0_0_i_reg_218.read().range(1-1, 0);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_xor_ln182_fu_319_p2() {
    xor_ln182_fu_319_p2 = (i1_0_reg_195.read() ^ ap_const_lv2_3);
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln125_fu_582_p1() {
    zext_ln125_fu_582_p1 = esl_zext<7,6>(i2_0_i_reg_240.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln126_1_fu_629_p1() {
    zext_ln126_1_fu_629_p1 = esl_zext<64,32>(sext_ln126_1_fu_626_p1.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln126_2_fu_530_p1() {
    zext_ln126_2_fu_530_p1 = esl_zext<7,6>(shl_ln_fu_522_p3.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln126_3_fu_560_p1() {
    zext_ln126_3_fu_560_p1 = esl_zext<10,9>(shl_ln126_1_fu_552_p3.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln126_4_fu_572_p1() {
    zext_ln126_4_fu_572_p1 = esl_zext<10,7>(shl_ln126_2_fu_564_p3.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln126_5_fu_603_p1() {
    zext_ln126_5_fu_603_p1 = esl_zext<10,7>(add_ln126_2_fu_598_p2.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln126_6_fu_617_p1() {
    zext_ln126_6_fu_617_p1 = esl_zext<10,7>(add_ln126_3_fu_612_p2.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln126_fu_637_p1() {
    zext_ln126_fu_637_p1 = esl_zext<64,32>(sext_ln126_fu_634_p1.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln133_fu_680_p1() {
    zext_ln133_fu_680_p1 = esl_zext<8,7>(shl_ln134_1_fu_662_p3.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln134_1_fu_670_p1() {
    zext_ln134_1_fu_670_p1 = esl_zext<9,7>(shl_ln134_1_fu_662_p3.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln134_2_fu_704_p1() {
    zext_ln134_2_fu_704_p1 = esl_zext<9,7>(or_ln_fu_696_p3.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln134_fu_726_p1() {
    zext_ln134_fu_726_p1 = esl_zext<64,9>(add_ln134_reg_941.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln179_fu_291_p1() {
    zext_ln179_fu_291_p1 = esl_zext<64,6>(i0_0_reg_183.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln182_1_fu_365_p1() {
    zext_ln182_1_fu_365_p1 = esl_zext<64,8>(add_ln182_reg_765.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln182_fu_333_p1() {
    zext_ln182_fu_333_p1 = esl_zext<8,7>(tmp_2_fu_325_p3.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln187_1_fu_356_p1() {
    zext_ln187_1_fu_356_p1 = esl_zext<8,7>(tmp_3_fu_348_p3.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln187_2_fu_369_p1() {
    zext_ln187_2_fu_369_p1 = esl_zext<64,8>(add_ln187_1_reg_776.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln187_fu_373_p1() {
    zext_ln187_fu_373_p1 = esl_zext<7,2>(add_ln187_reg_770.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln203_10_fu_722_p1() {
    zext_ln203_10_fu_722_p1 = esl_zext<64,8>(add_ln203_6_reg_946.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln203_1_fu_300_p1() {
    zext_ln203_1_fu_300_p1 = esl_zext<8,6>(i0_0_reg_183.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln203_2_fu_390_p1() {
    zext_ln203_2_fu_390_p1 = esl_zext<64,12>(add_ln203_fu_385_p2.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln203_3_fu_455_p1() {
    zext_ln203_3_fu_455_p1 = esl_zext<8,7>(tmp_6_fu_447_p3.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln203_4_fu_502_p1() {
    zext_ln203_4_fu_502_p1 = esl_zext<64,8>(add_ln203_1_reg_825.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln203_5_fu_415_p1() {
    zext_ln203_5_fu_415_p1 = esl_zext<7,6>(tmp_7_fu_407_p3.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln203_6_fu_498_p1() {
    zext_ln203_6_fu_498_p1 = esl_zext<64,12>(add_ln203_3_reg_835.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln203_7_fu_432_p1() {
    zext_ln203_7_fu_432_p1 = esl_zext<7,6>(tmp_10_fu_424_p3.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln203_8_fu_494_p1() {
    zext_ln203_8_fu_494_p1 = esl_zext<64,12>(add_ln203_5_reg_840.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln203_9_fu_713_p1() {
    zext_ln203_9_fu_713_p1 = esl_zext<8,6>(i22_0_i_reg_262.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_zext_ln203_fu_296_p1() {
    zext_ln203_fu_296_p1 = esl_zext<12,6>(i0_0_reg_183.read());
}

void cnnshift_arr_buffer_ap_fixed_ap_fixed_config9_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln177_fu_279_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state14;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln180_fu_313_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(icmp_ln189_fu_395_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 8192 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln122_fu_506_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state20;
            } else {
                ap_NS_fsm = ap_ST_fsm_state15;
            }
            break;
        case 16384 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln124_fu_540_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state14;
            } else {
                ap_NS_fsm = ap_ST_fsm_state16;
            }
            break;
        case 32768 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln125_fu_586_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state15;
            } else {
                ap_NS_fsm = ap_ST_fsm_state17;
            }
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 524288 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln131_fu_642_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state21;
            }
            break;
        case 1048576 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln133_fu_684_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state20;
            } else {
                ap_NS_fsm = ap_ST_fsm_state22;
            }
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<24>) ("XXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

