// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_ST_fsm_state1 = "1";
const sc_lv<7> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<7> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_ST_fsm_state8 = "100";
const sc_lv<7> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_ST_fsm_state9 = "1000";
const sc_lv<7> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_ST_fsm_state10 = "10000";
const sc_lv<7> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_ST_fsm_state11 = "100000";
const sc_lv<7> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_ST_fsm_state12 = "1000000";
const bool dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_boolean_1 = true;
const sc_lv<32> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv32_1 = "1";
const bool dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_boolean_0 = false;
const sc_lv<1> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv1_0 = "0";
const sc_lv<32> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv32_2 = "10";
const sc_lv<32> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv32_3 = "11";
const sc_lv<32> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv32_4 = "100";
const sc_lv<32> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv32_5 = "101";
const sc_lv<32> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv32_6 = "110";
const sc_lv<1> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv1_1 = "1";
const sc_lv<16> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv16_FEBD = "1111111010111101";
const sc_lv<16> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv16_FCE1 = "1111110011100001";
const sc_lv<16> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv16_FF96 = "1111111110010110";
const sc_lv<16> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv16_28 = "101000";
const sc_lv<16> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv16_FD66 = "1111110101100110";
const sc_lv<12> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv12_0 = "000000000000";
const sc_lv<12> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv12_900 = "100100000000";
const sc_lv<12> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv12_1 = "1";
const sc_lv<32> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv32_B = "1011";
const sc_lv<32> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv32_C = "1100";
const sc_lv<32> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv32_11 = "10001";
const sc_lv<32> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv32_12 = "10010";
const sc_lv<32> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv32_17 = "10111";
const sc_lv<32> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv32_18 = "11000";
const sc_lv<32> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv32_1C = "11100";
const sc_lv<32> dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::ap_const_lv32_14 = "10100";

dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    w17_V_U = new dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s_w17_V("w17_V_U");
    w17_V_U->clk(ap_clk);
    w17_V_U->reset(ap_rst);
    w17_V_U->address0(w17_V_address0);
    w17_V_U->ce0(w17_V_ce0);
    w17_V_U->q0(w17_V_q0);
    myproject_axi_mul_5s_16s_21_2_1_U258 = new myproject_axi_mul_5s_16s_21_2_1<1,2,5,16,21>("myproject_axi_mul_5s_16s_21_2_1_U258");
    myproject_axi_mul_5s_16s_21_2_1_U258->clk(ap_clk);
    myproject_axi_mul_5s_16s_21_2_1_U258->reset(ap_rst);
    myproject_axi_mul_5s_16s_21_2_1_U258->din0(tmp_1_reg_405);
    myproject_axi_mul_5s_16s_21_2_1_U258->din1(grp_fu_261_p1);
    myproject_axi_mul_5s_16s_21_2_1_U258->ce(grp_fu_261_ce);
    myproject_axi_mul_5s_16s_21_2_1_U258->dout(grp_fu_261_p2);
    myproject_axi_mul_mul_6s_16s_21_3_1_U259 = new myproject_axi_mul_mul_6s_16s_21_3_1<1,3,6,16,21>("myproject_axi_mul_mul_6s_16s_21_3_1_U259");
    myproject_axi_mul_mul_6s_16s_21_3_1_U259->clk(ap_clk);
    myproject_axi_mul_mul_6s_16s_21_3_1_U259->reset(ap_rst);
    myproject_axi_mul_mul_6s_16s_21_3_1_U259->din0(trunc_ln450_reg_385);
    myproject_axi_mul_mul_6s_16s_21_3_1_U259->din1(grp_fu_342_p1);
    myproject_axi_mul_mul_6s_16s_21_3_1_U259->ce(grp_fu_342_ce);
    myproject_axi_mul_mul_6s_16s_21_3_1_U259->dout(grp_fu_342_p2);
    myproject_axi_mul_mul_6s_16s_21_3_1_U260 = new myproject_axi_mul_mul_6s_16s_21_3_1<1,3,6,16,21>("myproject_axi_mul_mul_6s_16s_21_3_1_U260");
    myproject_axi_mul_mul_6s_16s_21_3_1_U260->clk(ap_clk);
    myproject_axi_mul_mul_6s_16s_21_3_1_U260->reset(ap_rst);
    myproject_axi_mul_mul_6s_16s_21_3_1_U260->din0(tmp_5_reg_390);
    myproject_axi_mul_mul_6s_16s_21_3_1_U260->din1(grp_fu_348_p1);
    myproject_axi_mul_mul_6s_16s_21_3_1_U260->ce(grp_fu_348_ce);
    myproject_axi_mul_mul_6s_16s_21_3_1_U260->dout(grp_fu_348_p2);
    myproject_axi_mul_mul_6s_16s_21_3_1_U261 = new myproject_axi_mul_mul_6s_16s_21_3_1<1,3,6,16,21>("myproject_axi_mul_mul_6s_16s_21_3_1_U261");
    myproject_axi_mul_mul_6s_16s_21_3_1_U261->clk(ap_clk);
    myproject_axi_mul_mul_6s_16s_21_3_1_U261->reset(ap_rst);
    myproject_axi_mul_mul_6s_16s_21_3_1_U261->din0(tmp_6_reg_395);
    myproject_axi_mul_mul_6s_16s_21_3_1_U261->din1(grp_fu_354_p1);
    myproject_axi_mul_mul_6s_16s_21_3_1_U261->ce(grp_fu_354_ce);
    myproject_axi_mul_mul_6s_16s_21_3_1_U261->dout(grp_fu_354_p2);
    myproject_axi_mul_mul_6s_16s_21_3_1_U262 = new myproject_axi_mul_mul_6s_16s_21_3_1<1,3,6,16,21>("myproject_axi_mul_mul_6s_16s_21_3_1_U262");
    myproject_axi_mul_mul_6s_16s_21_3_1_U262->clk(ap_clk);
    myproject_axi_mul_mul_6s_16s_21_3_1_U262->reset(ap_rst);
    myproject_axi_mul_mul_6s_16s_21_3_1_U262->din0(tmp_7_reg_400);
    myproject_axi_mul_mul_6s_16s_21_3_1_U262->din1(grp_fu_360_p1);
    myproject_axi_mul_mul_6s_16s_21_3_1_U262->ce(grp_fu_360_ce);
    myproject_axi_mul_mul_6s_16s_21_3_1_U262->dout(grp_fu_360_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln703_1_fu_306_p2);
    sensitive << ( tmp_V_13_reg_145 );
    sensitive << ( trunc_ln708_1_fu_297_p4 );

    SC_METHOD(thread_add_ln703_2_fu_321_p2);
    sensitive << ( tmp_V_14_reg_132 );
    sensitive << ( trunc_ln708_2_fu_312_p4 );

    SC_METHOD(thread_add_ln703_3_fu_336_p2);
    sensitive << ( tmp_V_15_reg_119 );
    sensitive << ( trunc_ln708_3_fu_327_p4 );

    SC_METHOD(thread_add_ln703_4_fu_277_p2);
    sensitive << ( trunc_ln708_4_reg_444 );
    sensitive << ( ap_phi_mux_tmp_V_16_phi_fu_111_p4 );

    SC_METHOD(thread_add_ln703_fu_291_p2);
    sensitive << ( tmp_V_reg_158 );
    sensitive << ( trunc_ln_fu_282_p4 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln442_reg_366 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln442_reg_366 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( icmp_ln442_reg_366 );

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter5);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln442_fu_182_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( res_V_V_full_n );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_ap_phi_mux_tmp_V_16_phi_fu_111_p4);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_V_16_reg_106 );
    sensitive << ( icmp_ln442_reg_366_pp0_iter4_reg );
    sensitive << ( add_ln703_4_reg_469 );
    sensitive << ( ap_enable_reg_pp0_iter5 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_data_V_V_blk_n);
    sensitive << ( data_V_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln442_reg_366 );

    SC_METHOD(thread_data_V_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln442_reg_366 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_261_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_261_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1116_cast_fu_243_p1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_grp_fu_342_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_342_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1116_cast_fu_243_p1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_grp_fu_348_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_348_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1116_cast_fu_243_p1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_grp_fu_354_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_354_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1116_cast_fu_243_p1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_grp_fu_360_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_360_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1116_cast_fu_243_p1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_i_in_fu_188_p2);
    sensitive << ( i_in_0_reg_171 );

    SC_METHOD(thread_icmp_ln442_fu_182_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( i_in_0_reg_171 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( res_V_V_full_n );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_res_V_V_blk_n);
    sensitive << ( res_V_V_full_n );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_res_V_V_din);
    sensitive << ( res_V_V_full_n );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_V_16_reg_106 );
    sensitive << ( tmp_V_15_reg_119 );
    sensitive << ( tmp_V_14_reg_132 );
    sensitive << ( tmp_V_13_reg_145 );
    sensitive << ( tmp_V_reg_158 );

    SC_METHOD(thread_res_V_V_write);
    sensitive << ( res_V_V_full_n );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_sext_ln1116_cast_fu_243_p1);
    sensitive << ( tmp_V_17_reg_380 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_trunc_ln450_fu_199_p1);
    sensitive << ( w17_V_q0 );

    SC_METHOD(thread_trunc_ln708_1_fu_297_p4);
    sensitive << ( mul_ln1118_1_reg_454 );

    SC_METHOD(thread_trunc_ln708_2_fu_312_p4);
    sensitive << ( mul_ln1118_2_reg_459 );

    SC_METHOD(thread_trunc_ln708_3_fu_327_p4);
    sensitive << ( mul_ln1118_3_reg_464 );

    SC_METHOD(thread_trunc_ln_fu_282_p4);
    sensitive << ( mul_ln1118_reg_449 );

    SC_METHOD(thread_w17_V_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( zext_ln450_fu_194_p1 );

    SC_METHOD(thread_w17_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_zext_ln450_fu_194_p1);
    sensitive << ( i_in_0_reg_171 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( res_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( icmp_ln442_fu_182_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0000001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, data_V_V_dout, "(port)data_V_V_dout");
    sc_trace(mVcdFile, data_V_V_empty_n, "(port)data_V_V_empty_n");
    sc_trace(mVcdFile, data_V_V_read, "(port)data_V_V_read");
    sc_trace(mVcdFile, res_V_V_din, "(port)res_V_V_din");
    sc_trace(mVcdFile, res_V_V_full_n, "(port)res_V_V_full_n");
    sc_trace(mVcdFile, res_V_V_write, "(port)res_V_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, w17_V_address0, "w17_V_address0");
    sc_trace(mVcdFile, w17_V_ce0, "w17_V_ce0");
    sc_trace(mVcdFile, w17_V_q0, "w17_V_q0");
    sc_trace(mVcdFile, data_V_V_blk_n, "data_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln442_reg_366, "icmp_ln442_reg_366");
    sc_trace(mVcdFile, res_V_V_blk_n, "res_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, tmp_V_16_reg_106, "tmp_V_16_reg_106");
    sc_trace(mVcdFile, tmp_V_15_reg_119, "tmp_V_15_reg_119");
    sc_trace(mVcdFile, tmp_V_14_reg_132, "tmp_V_14_reg_132");
    sc_trace(mVcdFile, tmp_V_13_reg_145, "tmp_V_13_reg_145");
    sc_trace(mVcdFile, tmp_V_reg_158, "tmp_V_reg_158");
    sc_trace(mVcdFile, i_in_0_reg_171, "i_in_0_reg_171");
    sc_trace(mVcdFile, icmp_ln442_fu_182_p2, "icmp_ln442_fu_182_p2");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter3, "ap_block_state5_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter4, "ap_block_state6_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter5, "ap_block_state7_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, icmp_ln442_reg_366_pp0_iter1_reg, "icmp_ln442_reg_366_pp0_iter1_reg");
    sc_trace(mVcdFile, icmp_ln442_reg_366_pp0_iter2_reg, "icmp_ln442_reg_366_pp0_iter2_reg");
    sc_trace(mVcdFile, icmp_ln442_reg_366_pp0_iter3_reg, "icmp_ln442_reg_366_pp0_iter3_reg");
    sc_trace(mVcdFile, icmp_ln442_reg_366_pp0_iter4_reg, "icmp_ln442_reg_366_pp0_iter4_reg");
    sc_trace(mVcdFile, i_in_fu_188_p2, "i_in_fu_188_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_V_17_reg_380, "tmp_V_17_reg_380");
    sc_trace(mVcdFile, trunc_ln450_fu_199_p1, "trunc_ln450_fu_199_p1");
    sc_trace(mVcdFile, trunc_ln450_reg_385, "trunc_ln450_reg_385");
    sc_trace(mVcdFile, tmp_5_reg_390, "tmp_5_reg_390");
    sc_trace(mVcdFile, tmp_6_reg_395, "tmp_6_reg_395");
    sc_trace(mVcdFile, tmp_7_reg_400, "tmp_7_reg_400");
    sc_trace(mVcdFile, tmp_1_reg_405, "tmp_1_reg_405");
    sc_trace(mVcdFile, sext_ln1116_cast_fu_243_p1, "sext_ln1116_cast_fu_243_p1");
    sc_trace(mVcdFile, trunc_ln708_4_reg_444, "trunc_ln708_4_reg_444");
    sc_trace(mVcdFile, grp_fu_342_p2, "grp_fu_342_p2");
    sc_trace(mVcdFile, mul_ln1118_reg_449, "mul_ln1118_reg_449");
    sc_trace(mVcdFile, grp_fu_348_p2, "grp_fu_348_p2");
    sc_trace(mVcdFile, mul_ln1118_1_reg_454, "mul_ln1118_1_reg_454");
    sc_trace(mVcdFile, grp_fu_354_p2, "grp_fu_354_p2");
    sc_trace(mVcdFile, mul_ln1118_2_reg_459, "mul_ln1118_2_reg_459");
    sc_trace(mVcdFile, grp_fu_360_p2, "grp_fu_360_p2");
    sc_trace(mVcdFile, mul_ln1118_3_reg_464, "mul_ln1118_3_reg_464");
    sc_trace(mVcdFile, add_ln703_4_fu_277_p2, "add_ln703_4_fu_277_p2");
    sc_trace(mVcdFile, add_ln703_4_reg_469, "add_ln703_4_reg_469");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, add_ln703_fu_291_p2, "add_ln703_fu_291_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, add_ln703_1_fu_306_p2, "add_ln703_1_fu_306_p2");
    sc_trace(mVcdFile, add_ln703_2_fu_321_p2, "add_ln703_2_fu_321_p2");
    sc_trace(mVcdFile, add_ln703_3_fu_336_p2, "add_ln703_3_fu_336_p2");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_phi_mux_tmp_V_16_phi_fu_111_p4, "ap_phi_mux_tmp_V_16_phi_fu_111_p4");
    sc_trace(mVcdFile, zext_ln450_fu_194_p1, "zext_ln450_fu_194_p1");
    sc_trace(mVcdFile, grp_fu_261_p1, "grp_fu_261_p1");
    sc_trace(mVcdFile, grp_fu_261_p2, "grp_fu_261_p2");
    sc_trace(mVcdFile, trunc_ln_fu_282_p4, "trunc_ln_fu_282_p4");
    sc_trace(mVcdFile, trunc_ln708_1_fu_297_p4, "trunc_ln708_1_fu_297_p4");
    sc_trace(mVcdFile, trunc_ln708_2_fu_312_p4, "trunc_ln708_2_fu_312_p4");
    sc_trace(mVcdFile, trunc_ln708_3_fu_327_p4, "trunc_ln708_3_fu_327_p4");
    sc_trace(mVcdFile, grp_fu_342_p1, "grp_fu_342_p1");
    sc_trace(mVcdFile, grp_fu_348_p1, "grp_fu_348_p1");
    sc_trace(mVcdFile, grp_fu_354_p1, "grp_fu_354_p1");
    sc_trace(mVcdFile, grp_fu_360_p1, "grp_fu_360_p1");
    sc_trace(mVcdFile, grp_fu_261_ce, "grp_fu_261_ce");
    sc_trace(mVcdFile, grp_fu_342_ce, "grp_fu_342_ce");
    sc_trace(mVcdFile, grp_fu_348_ce, "grp_fu_348_ce");
    sc_trace(mVcdFile, grp_fu_354_ce, "grp_fu_354_ce");
    sc_trace(mVcdFile, grp_fu_360_ce, "grp_fu_360_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::~dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete w17_V_U;
    delete myproject_axi_mul_5s_16s_21_2_1_U258;
    delete myproject_axi_mul_mul_6s_16s_21_3_1_U259;
    delete myproject_axi_mul_mul_6s_16s_21_3_1_U260;
    delete myproject_axi_mul_mul_6s_16s_21_3_1_U261;
    delete myproject_axi_mul_mul_6s_16s_21_3_1_U262;
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
                    esl_seteq<1,1,1>(res_V_V_full_n.read(), ap_const_logic_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter5 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln442_fu_182_p2.read()))) {
        i_in_0_reg_171 = i_in_fu_188_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i_in_0_reg_171 = ap_const_lv12_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln442_reg_366_pp0_iter4_reg.read()))) {
        tmp_V_13_reg_145 = add_ln703_1_fu_306_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        tmp_V_13_reg_145 = ap_const_lv16_28;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln442_reg_366_pp0_iter4_reg.read()))) {
        tmp_V_14_reg_132 = add_ln703_2_fu_321_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        tmp_V_14_reg_132 = ap_const_lv16_FF96;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln442_reg_366_pp0_iter4_reg.read()))) {
        tmp_V_15_reg_119 = add_ln703_3_fu_336_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        tmp_V_15_reg_119 = ap_const_lv16_FCE1;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln442_reg_366_pp0_iter4_reg.read()))) {
        tmp_V_16_reg_106 = add_ln703_4_reg_469.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        tmp_V_16_reg_106 = ap_const_lv16_FEBD;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln442_reg_366_pp0_iter4_reg.read()))) {
        tmp_V_reg_158 = add_ln703_fu_291_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        tmp_V_reg_158 = ap_const_lv16_FD66;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln442_reg_366_pp0_iter3_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()))) {
        add_ln703_4_reg_469 = add_ln703_4_fu_277_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln442_reg_366 = icmp_ln442_fu_182_p2.read();
        icmp_ln442_reg_366_pp0_iter1_reg = icmp_ln442_reg_366.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        icmp_ln442_reg_366_pp0_iter2_reg = icmp_ln442_reg_366_pp0_iter1_reg.read();
        icmp_ln442_reg_366_pp0_iter3_reg = icmp_ln442_reg_366_pp0_iter2_reg.read();
        icmp_ln442_reg_366_pp0_iter4_reg = icmp_ln442_reg_366_pp0_iter3_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln442_reg_366_pp0_iter3_reg.read()))) {
        mul_ln1118_1_reg_454 = grp_fu_348_p2.read();
        mul_ln1118_2_reg_459 = grp_fu_354_p2.read();
        mul_ln1118_3_reg_464 = grp_fu_360_p2.read();
        mul_ln1118_reg_449 = grp_fu_342_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(icmp_ln442_reg_366.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_1_reg_405 = w17_V_q0.read().range(28, 24);
        tmp_5_reg_390 = w17_V_q0.read().range(11, 6);
        tmp_6_reg_395 = w17_V_q0.read().range(17, 12);
        tmp_7_reg_400 = w17_V_q0.read().range(23, 18);
        tmp_V_17_reg_380 = data_V_V_dout.read();
        trunc_ln450_reg_385 = trunc_ln450_fu_199_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln442_reg_366_pp0_iter2_reg.read()))) {
        trunc_ln708_4_reg_444 = grp_fu_261_p2.read().range(20, 5);
    }
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_add_ln703_1_fu_306_p2() {
    add_ln703_1_fu_306_p2 = (!tmp_V_13_reg_145.read().is_01() || !trunc_ln708_1_fu_297_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_V_13_reg_145.read()) + sc_biguint<16>(trunc_ln708_1_fu_297_p4.read()));
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_add_ln703_2_fu_321_p2() {
    add_ln703_2_fu_321_p2 = (!tmp_V_14_reg_132.read().is_01() || !trunc_ln708_2_fu_312_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_V_14_reg_132.read()) + sc_biguint<16>(trunc_ln708_2_fu_312_p4.read()));
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_add_ln703_3_fu_336_p2() {
    add_ln703_3_fu_336_p2 = (!tmp_V_15_reg_119.read().is_01() || !trunc_ln708_3_fu_327_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_V_15_reg_119.read()) + sc_biguint<16>(trunc_ln708_3_fu_327_p4.read()));
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_add_ln703_4_fu_277_p2() {
    add_ln703_4_fu_277_p2 = (!ap_phi_mux_tmp_V_16_phi_fu_111_p4.read().is_01() || !trunc_ln708_4_reg_444.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_phi_mux_tmp_V_16_phi_fu_111_p4.read()) + sc_biguint<16>(trunc_ln708_4_reg_444.read()));
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_add_ln703_fu_291_p2() {
    add_ln703_fu_291_p2 = (!tmp_V_reg_158.read().is_01() || !trunc_ln_fu_282_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_V_reg_158.read()) + sc_biguint<16>(trunc_ln_fu_282_p4.read()));
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[4];
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[5];
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[6];
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[2];
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[3];
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(icmp_ln442_reg_366.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read()));
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(icmp_ln442_reg_366.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read()));
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = (esl_seteq<1,1,1>(icmp_ln442_reg_366.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_V_empty_n.read()));
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_block_state5_pp0_stage0_iter3() {
    ap_block_state5_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_block_state6_pp0_stage0_iter4() {
    ap_block_state6_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_block_state7_pp0_stage0_iter5() {
    ap_block_state7_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln442_fu_182_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(res_V_V_full_n.read(), ap_const_logic_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_phi_mux_tmp_V_16_phi_fu_111_p4() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln442_reg_366_pp0_iter4_reg.read()))) {
        ap_phi_mux_tmp_V_16_phi_fu_111_p4 = add_ln703_4_reg_469.read();
    } else {
        ap_phi_mux_tmp_V_16_phi_fu_111_p4 = tmp_V_16_reg_106.read();
    }
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_data_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln442_reg_366.read(), ap_const_lv1_0))) {
        data_V_V_blk_n = data_V_V_empty_n.read();
    } else {
        data_V_V_blk_n = ap_const_logic_1;
    }
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_data_V_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln442_reg_366.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_V_read = ap_const_logic_1;
    } else {
        data_V_V_read = ap_const_logic_0;
    }
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_grp_fu_261_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_261_ce = ap_const_logic_1;
    } else {
        grp_fu_261_ce = ap_const_logic_0;
    }
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_grp_fu_261_p1() {
    grp_fu_261_p1 =  (sc_lv<16>) (sext_ln1116_cast_fu_243_p1.read());
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_grp_fu_342_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_342_ce = ap_const_logic_1;
    } else {
        grp_fu_342_ce = ap_const_logic_0;
    }
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_grp_fu_342_p1() {
    grp_fu_342_p1 =  (sc_lv<16>) (sext_ln1116_cast_fu_243_p1.read());
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_grp_fu_348_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_348_ce = ap_const_logic_1;
    } else {
        grp_fu_348_ce = ap_const_logic_0;
    }
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_grp_fu_348_p1() {
    grp_fu_348_p1 =  (sc_lv<16>) (sext_ln1116_cast_fu_243_p1.read());
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_grp_fu_354_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_354_ce = ap_const_logic_1;
    } else {
        grp_fu_354_ce = ap_const_logic_0;
    }
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_grp_fu_354_p1() {
    grp_fu_354_p1 =  (sc_lv<16>) (sext_ln1116_cast_fu_243_p1.read());
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_grp_fu_360_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_360_ce = ap_const_logic_1;
    } else {
        grp_fu_360_ce = ap_const_logic_0;
    }
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_grp_fu_360_p1() {
    grp_fu_360_p1 =  (sc_lv<16>) (sext_ln1116_cast_fu_243_p1.read());
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_i_in_fu_188_p2() {
    i_in_fu_188_p2 = (!i_in_0_reg_171.read().is_01() || !ap_const_lv12_1.is_01())? sc_lv<12>(): (sc_biguint<12>(i_in_0_reg_171.read()) + sc_biguint<12>(ap_const_lv12_1));
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_icmp_ln442_fu_182_p2() {
    icmp_ln442_fu_182_p2 = (!i_in_0_reg_171.read().is_01() || !ap_const_lv12_900.is_01())? sc_lv<1>(): sc_lv<1>(i_in_0_reg_171.read() == ap_const_lv12_900);
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(res_V_V_full_n.read(), ap_const_logic_1))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_res_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        res_V_V_blk_n = res_V_V_full_n.read();
    } else {
        res_V_V_blk_n = ap_const_logic_1;
    }
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_res_V_V_din() {
    if (esl_seteq<1,1,1>(res_V_V_full_n.read(), ap_const_logic_1)) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
            res_V_V_din = tmp_V_16_reg_106.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
            res_V_V_din = tmp_V_15_reg_119.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
            res_V_V_din = tmp_V_14_reg_132.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
            res_V_V_din = tmp_V_13_reg_145.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
            res_V_V_din = tmp_V_reg_158.read();
        } else {
            res_V_V_din = "XXXXXXXXXXXXXXXX";
        }
    } else {
        res_V_V_din = "XXXXXXXXXXXXXXXX";
    }
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_res_V_V_write() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(res_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(res_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
          esl_seteq<1,1,1>(res_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(res_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
          esl_seteq<1,1,1>(res_V_V_full_n.read(), ap_const_logic_1)))) {
        res_V_V_write = ap_const_logic_1;
    } else {
        res_V_V_write = ap_const_logic_0;
    }
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_sext_ln1116_cast_fu_243_p1() {
    sext_ln1116_cast_fu_243_p1 = esl_sext<21,16>(tmp_V_17_reg_380.read());
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_start_out() {
    start_out = real_start.read();
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_trunc_ln450_fu_199_p1() {
    trunc_ln450_fu_199_p1 = w17_V_q0.read().range(6-1, 0);
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_trunc_ln708_1_fu_297_p4() {
    trunc_ln708_1_fu_297_p4 = mul_ln1118_1_reg_454.read().range(20, 5);
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_trunc_ln708_2_fu_312_p4() {
    trunc_ln708_2_fu_312_p4 = mul_ln1118_2_reg_459.read().range(20, 5);
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_trunc_ln708_3_fu_327_p4() {
    trunc_ln708_3_fu_327_p4 = mul_ln1118_3_reg_464.read().range(20, 5);
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_trunc_ln_fu_282_p4() {
    trunc_ln_fu_282_p4 = mul_ln1118_reg_449.read().range(20, 5);
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_w17_V_address0() {
    w17_V_address0 =  (sc_lv<12>) (zext_ln450_fu_194_p1.read());
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_w17_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        w17_V_ce0 = ap_const_logic_1;
    } else {
        w17_V_ce0 = ap_const_logic_0;
    }
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_zext_ln450_fu_194_p1() {
    zext_ln450_fu_194_p1 = esl_zext<64,12>(i_in_0_reg_171.read());
}

void dense_ss_ap_fixed_ap_fixed_16_4_5_3_0_config17_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln442_fu_182_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln442_fu_182_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(res_V_V_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(res_V_V_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(res_V_V_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(res_V_V_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(res_V_V_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<7>) ("XXXXXXX");
            break;
    }
}

}

